// Code generated by gen-holidays from definitions/ar.yaml@v6.1.1. DO NOT EDIT.

package definitions_test

import (
	"testing"

	holidays "github.com/ppeble/go-holidays/pkg"
)

func TestAR_000_AñoNuevo(t *testing.T) {
	dates := []string{"2016-01-01"}
	opts := holidays.Options{Regions: []string{"ar"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Año Nuevo") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Año Nuevo", hols)
		}
	}
}

func TestAR_001_CarnavalLunes(t *testing.T) {
	dates := []string{"2016-02-08"}
	opts := holidays.Options{Regions: []string{"ar"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Carnaval Lunes") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Carnaval Lunes", hols)
		}
	}
}

func TestAR_002_CarnavalMartes(t *testing.T) {
	dates := []string{"2016-02-09"}
	opts := holidays.Options{Regions: []string{"ar"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Carnaval Martes") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Carnaval Martes", hols)
		}
	}
}

func TestAR_003_CarnavalLunes(t *testing.T) {
	dates := []string{"2017-02-27"}
	opts := holidays.Options{Regions: []string{"ar"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Carnaval Lunes") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Carnaval Lunes", hols)
		}
	}
}

func TestAR_004_CarnavalMartes(t *testing.T) {
	dates := []string{"2017-02-28"}
	opts := holidays.Options{Regions: []string{"ar"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Carnaval Martes") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Carnaval Martes", hols)
		}
	}
}

func TestAR_005_CarnavalLunes(t *testing.T) {
	dates := []string{"2018-02-12"}
	opts := holidays.Options{Regions: []string{"ar"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Carnaval Lunes") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Carnaval Lunes", hols)
		}
	}
}

func TestAR_006_CarnavalMartes(t *testing.T) {
	dates := []string{"2018-02-13"}
	opts := holidays.Options{Regions: []string{"ar"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Carnaval Martes") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Carnaval Martes", hols)
		}
	}
}

func TestAR_007_DíaNacionalDeLaMemoriaPorLaVerdadYLaJusticia(t *testing.T) {
	dates := []string{"2016-03-24"}
	opts := holidays.Options{Regions: []string{"ar"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Día Nacional de la Memoria por la Verdad y la Justicia") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día Nacional de la Memoria por la Verdad y la Justicia", hols)
		}
	}
}

func TestAR_008_ViernesSanto(t *testing.T) {
	dates := []string{"2016-03-25"}
	opts := holidays.Options{Regions: []string{"ar"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Viernes Santo") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Viernes Santo", hols)
		}
	}
}

func TestAR_009_DíaDelVeteranoYDeLosCaídosEnLaGuerraDeMalvinas(t *testing.T) {
	dates := []string{"2016-04-02"}
	opts := holidays.Options{Regions: []string{"ar"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Día del Veterano y de los Caídos en la Guerra de Malvinas") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día del Veterano y de los Caídos en la Guerra de Malvinas", hols)
		}
	}
}

func TestAR_010_DíaDelTrabajador(t *testing.T) {
	dates := []string{"2016-05-01"}
	opts := holidays.Options{Regions: []string{"ar"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Día del Trabajador") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día del Trabajador", hols)
		}
	}
}

func TestAR_011_DíaDeLaRevoluciónDeMayo(t *testing.T) {
	dates := []string{"2016-05-25"}
	opts := holidays.Options{Regions: []string{"ar"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Día de la Revolución de Mayo") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de la Revolución de Mayo", hols)
		}
	}
}

func TestAR_012_PasoALaInmortalidadDelGeneralMartínMiguelDeGüemes(t *testing.T) {
	dates := []string{"2020-06-15", "2021-06-21"}
	opts := holidays.Options{Regions: []string{"ar"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Paso a la Inmortalidad del General Martín Miguel de Güemes") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Paso a la Inmortalidad del General Martín Miguel de Güemes", hols)
		}
	}
}

func TestAR_013_Negative(t *testing.T) {
	dates := []string{"2020-06-17", "2021-06-17"}
	opts := holidays.Options{Regions: []string{"ar"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if len(hols) > 0 {
			t.Errorf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols)
		}
	}
}

func TestAR_014_PasoALaInmortalidadDelGeneralMartínMiguelDeGüemes(t *testing.T) {
	dates := []string{"2016-06-20"}
	opts := holidays.Options{Regions: []string{"ar"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Paso a la Inmortalidad del General Martín Miguel de Güemes") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Paso a la Inmortalidad del General Martín Miguel de Güemes", hols)
		}
	}
}

func TestAR_015_DíaDeLaIndependencia(t *testing.T) {
	dates := []string{"2016-07-09"}
	opts := holidays.Options{Regions: []string{"ar"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Día de la Independencia") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de la Independencia", hols)
		}
	}
}

func TestAR_016_PasoALaInmortalidadDelGeneralJoséDeSanMartín(t *testing.T) {
	dates := []string{"2016-08-15", "2020-08-17", "2021-08-16"}
	opts := holidays.Options{Regions: []string{"ar"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Paso a la Inmortalidad del General José de San Martín") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Paso a la Inmortalidad del General José de San Martín", hols)
		}
	}
}

func TestAR_017_Negative(t *testing.T) {
	dates := []string{"2016-08-17", "2021-08-17"}
	opts := holidays.Options{Regions: []string{"ar"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if len(hols) > 0 {
			t.Errorf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols)
		}
	}
}

func TestAR_018_DíaDelRespetoALaDiversidadCultural(t *testing.T) {
	dates := []string{"2016-10-10", "2021-10-11"}
	opts := holidays.Options{Regions: []string{"ar"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Día del Respeto a la Diversidad Cultural") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día del Respeto a la Diversidad Cultural", hols)
		}
	}
}

func TestAR_019_Negative(t *testing.T) {
	dates := []string{"2021-10-12"}
	opts := holidays.Options{Regions: []string{"ar"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if len(hols) > 0 {
			t.Errorf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols)
		}
	}
}

func TestAR_020_DíaDeLaSoberaníaNacional(t *testing.T) {
	dates := []string{"2016-11-20"}
	opts := holidays.Options{Regions: []string{"ar"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Día de la Soberanía Nacional") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de la Soberanía Nacional", hols)
		}
	}
}

func TestAR_021_InmaculadaConcepciónDeMaría(t *testing.T) {
	dates := []string{"2016-12-08"}
	opts := holidays.Options{Regions: []string{"ar"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Inmaculada Concepción de María") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Inmaculada Concepción de María", hols)
		}
	}
}

func TestAR_022_FeriadoConFinesTurísticos(t *testing.T) {
	dates := []string{"2016-07-08", "2016-12-09", "2021-05-24", "2021-10-8", "2021-11-22"}
	opts := holidays.Options{Regions: []string{"ar"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Feriado con fines turísticos") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Feriado con fines turísticos", hols)
		}
	}
}

func TestAR_023_Navidad(t *testing.T) {
	dates := []string{"2016-12-25"}
	opts := holidays.Options{Regions: []string{"ar"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Navidad") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Navidad", hols)
		}
	}
}
