// Code generated by gen-holidays from definitions/at.yaml@v6.1.1. DO NOT EDIT.

package definitions_test

import (
	"testing"

	holidays "github.com/ppeble/go-holidays/pkg"
)

func TestAT_000_Neujahrstag(t *testing.T) {
	dates := []string{"2009-01-01"}
	opts := holidays.Options{Regions: []string{"at"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Neujahrstag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Neujahrstag", hols)
		}
	}
}

func TestAT_001_Ostermontag(t *testing.T) {
	dates := []string{"2009-04-13"}
	opts := holidays.Options{Regions: []string{"at"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Ostermontag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Ostermontag", hols)
		}
	}
}

func TestAT_002_ChristiHimmelfahrt(t *testing.T) {
	dates := []string{"2009-05-21"}
	opts := holidays.Options{Regions: []string{"at"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Christi Himmelfahrt") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christi Himmelfahrt", hols)
		}
	}
}

func TestAT_003_Pfingstmontag(t *testing.T) {
	dates := []string{"2009-06-01"}
	opts := holidays.Options{Regions: []string{"at"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Pfingstmontag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Pfingstmontag", hols)
		}
	}
}

func TestAT_004_Nationalfeiertag(t *testing.T) {
	dates := []string{"2009-10-26"}
	opts := holidays.Options{Regions: []string{"at"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Nationalfeiertag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Nationalfeiertag", hols)
		}
	}
}

func TestAT_005_MariäEmpfängnis(t *testing.T) {
	dates := []string{"2009-12-08"}
	opts := holidays.Options{Regions: []string{"at"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Mariä Empfängnis") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Mariä Empfängnis", hols)
		}
	}
}

func TestAT_006_1Weihnachtstag(t *testing.T) {
	dates := []string{"2009-12-25"}
	opts := holidays.Options{Regions: []string{"at"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "1. Weihnachtstag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "1. Weihnachtstag", hols)
		}
	}
}

func TestAT_007_2Weihnachtstag(t *testing.T) {
	dates := []string{"2009-12-26"}
	opts := holidays.Options{Regions: []string{"at"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "2. Weihnachtstag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "2. Weihnachtstag", hols)
		}
	}
}

func TestAT_008_Negative(t *testing.T) {
	dates := []string{"2010-05-08"}
	opts := holidays.Options{Regions: []string{"at"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if len(hols) > 0 {
			t.Errorf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols)
		}
	}
}

func TestAT_009_Fronleichnam(t *testing.T) {
	dates := []string{"2017-06-15"}
	opts := holidays.Options{Regions: []string{"at"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Fronleichnam") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Fronleichnam", hols)
		}
	}
}
