// Code generated by gen-holidays from definitions/bg.yaml@v6.1.1. DO NOT EDIT.

package definitions_test

import (
	"testing"

	holidays "github.com/ppeble/go-holidays/pkg"
)

func TestBG_000_NewYearSDay(t *testing.T) {
	dates := []string{"2015-01-01"}
	opts := holidays.Options{Regions: []string{"bg_en"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "New Year's Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols)
		}
	}
}

func TestBG_001_LiberationDay(t *testing.T) {
	dates := []string{"2015-03-03"}
	opts := holidays.Options{Regions: []string{"bg_en"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Liberation Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Liberation Day", hols)
		}
	}
}

func TestBG_002_GoodFriday(t *testing.T) {
	dates := []string{"2015-04-10"}
	opts := holidays.Options{Regions: []string{"bg_en"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Good Friday") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Good Friday", hols)
		}
	}
}

func TestBG_003_HolySaturday(t *testing.T) {
	dates := []string{"2015-04-11"}
	opts := holidays.Options{Regions: []string{"bg_en"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Holy Saturday") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Holy Saturday", hols)
		}
	}
}

func TestBG_004_EasterSunday(t *testing.T) {
	dates := []string{"2015-04-12"}
	opts := holidays.Options{Regions: []string{"bg_en"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Easter Sunday") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Easter Sunday", hols)
		}
	}
}

func TestBG_005_EasterMonday(t *testing.T) {
	dates := []string{"2015-04-13"}
	opts := holidays.Options{Regions: []string{"bg_en"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Easter Monday") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Easter Monday", hols)
		}
	}
}

func TestBG_006_LabourDay(t *testing.T) {
	dates := []string{"2015-05-01"}
	opts := holidays.Options{Regions: []string{"bg_en"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Labour Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Labour Day", hols)
		}
	}
}

func TestBG_007_StGeorgeSDay(t *testing.T) {
	dates := []string{"2015-05-06"}
	opts := holidays.Options{Regions: []string{"bg_en"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "St. George's Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "St. George's Day", hols)
		}
	}
}

func TestBG_008_SlavicLiteracyDay(t *testing.T) {
	dates := []string{"2015-05-24"}
	opts := holidays.Options{Regions: []string{"bg_en"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Slavic Literacy Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Slavic Literacy Day", hols)
		}
	}
}

func TestBG_009_UnificationDay(t *testing.T) {
	dates := []string{"2015-09-06"}
	opts := holidays.Options{Regions: []string{"bg_en"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Unification Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Unification Day", hols)
		}
	}
}

func TestBG_010_TheIndependenceDay(t *testing.T) {
	dates := []string{"2015-09-22"}
	opts := holidays.Options{Regions: []string{"bg_en"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "The Independence Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "The Independence Day", hols)
		}
	}
}

func TestBG_011_RevivalLeaderSDay(t *testing.T) {
	dates := []string{"2015-11-01"}
	opts := holidays.Options{Regions: []string{"bg_en"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Revival Leader's Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Revival Leader's Day", hols)
		}
	}
}

func TestBG_012_ChristmasEve(t *testing.T) {
	dates := []string{"2015-12-24"}
	opts := holidays.Options{Regions: []string{"bg_en"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Christmas Eve") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Eve", hols)
		}
	}
}

func TestBG_013_Christmas(t *testing.T) {
	dates := []string{"2015-12-25"}
	opts := holidays.Options{Regions: []string{"bg_en"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Christmas") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas", hols)
		}
	}
}

func TestBG_014_Christmas(t *testing.T) {
	dates := []string{"2015-12-26"}
	opts := holidays.Options{Regions: []string{"bg_en"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Christmas") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas", hols)
		}
	}
}
