// Code generated by gen-holidays from definitions/ch.yaml@v6.1.1. DO NOT EDIT.

package definitions_test

import (
	"testing"

	holidays "github.com/ppeble/go-holidays/pkg"
)

func TestCH_000_Neujahrstag(t *testing.T) {
	dates := []string{"2018-01-01"}
	opts := holidays.Options{Regions: []string{"ch"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Neujahrstag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Neujahrstag", hols)
		}
	}
}

func TestCH_001_Bundesfeiertag(t *testing.T) {
	dates := []string{"2012-08-01"}
	opts := holidays.Options{Regions: []string{"ch"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Bundesfeiertag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Bundesfeiertag", hols)
		}
	}
}

func TestCH_002_Weihnachten(t *testing.T) {
	dates := []string{"2012-12-25"}
	opts := holidays.Options{Regions: []string{"ch"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Weihnachten") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Weihnachten", hols)
		}
	}
}

func TestCH_003_Auffahrt(t *testing.T) {
	dates := []string{"2012-05-17"}
	opts := holidays.Options{Regions: []string{"ch"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Auffahrt") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Auffahrt", hols)
		}
	}
}

func TestCH_004_Bundesfeiertag(t *testing.T) {
	dates := []string{"2012-08-01"}
	opts := holidays.Options{Regions: []string{"ch_zh"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Bundesfeiertag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Bundesfeiertag", hols)
		}
	}
}

func TestCH_005_Weihnachten(t *testing.T) {
	dates := []string{"2012-12-25"}
	opts := holidays.Options{Regions: []string{"ch_zh"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Weihnachten") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Weihnachten", hols)
		}
	}
}

func TestCH_006_Auffahrt(t *testing.T) {
	dates := []string{"2012-05-17"}
	opts := holidays.Options{Regions: []string{"ch_zh"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Auffahrt") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Auffahrt", hols)
		}
	}
}

func TestCH_007_TagDerArbeit(t *testing.T) {
	dates := []string{"2012-05-01"}
	opts := holidays.Options{Regions: []string{"ch_zh"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Tag der Arbeit") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Tag der Arbeit", hols)
		}
	}
}

func TestCH_008_Stefanstag(t *testing.T) {
	dates := []string{"2012-12-26"}
	opts := holidays.Options{Regions: []string{"ch_zh"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Stefanstag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Stefanstag", hols)
		}
	}
}

func TestCH_009_LundiDuJeûneFédéral(t *testing.T) {
	dates := []string{"2012-09-17"}
	opts := holidays.Options{Regions: []string{"ch_vd"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Lundi du Jeûne fédéral") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Lundi du Jeûne fédéral", hols)
		}
	}
}

func TestCH_010_LundiDuJeûneFédéral(t *testing.T) {
	dates := []string{"2013-09-16"}
	opts := holidays.Options{Regions: []string{"ch_vd"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Lundi du Jeûne fédéral") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Lundi du Jeûne fédéral", hols)
		}
	}
}

func TestCH_011_LundiDuJeûneFédéral(t *testing.T) {
	dates := []string{"2014-09-22"}
	opts := holidays.Options{Regions: []string{"ch_vd"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Lundi du Jeûne fédéral") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Lundi du Jeûne fédéral", hols)
		}
	}
}

func TestCH_012_JeûneGenevois(t *testing.T) {
	dates := []string{"2012-09-06"}
	opts := holidays.Options{Regions: []string{"ch_ge"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Jeûne genevois") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Jeûne genevois", hols)
		}
	}
}

func TestCH_013_JeûneGenevois(t *testing.T) {
	dates := []string{"2013-09-05"}
	opts := holidays.Options{Regions: []string{"ch_ge"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Jeûne genevois") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Jeûne genevois", hols)
		}
	}
}

func TestCH_014_JeûneGenevois(t *testing.T) {
	dates := []string{"2014-09-11"}
	opts := holidays.Options{Regions: []string{"ch_ge"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Jeûne genevois") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Jeûne genevois", hols)
		}
	}
}

func TestCH_015_NäfelserFahrt(t *testing.T) {
	dates := []string{"2012-04-12"}
	opts := holidays.Options{Regions: []string{"ch_gl"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Näfelser Fahrt") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Näfelser Fahrt", hols)
		}
	}
}

func TestCH_016_NäfelserFahrt(t *testing.T) {
	dates := []string{"2013-04-04"}
	opts := holidays.Options{Regions: []string{"ch_gl"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Näfelser Fahrt") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Näfelser Fahrt", hols)
		}
	}
}

func TestCH_017_NäfelserFahrt(t *testing.T) {
	dates := []string{"2014-04-03"}
	opts := holidays.Options{Regions: []string{"ch_gl"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Näfelser Fahrt") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Näfelser Fahrt", hols)
		}
	}
}

func TestCH_018_Zibelemärit(t *testing.T) {
	dates := []string{"2014-11-24"}
	opts := holidays.Options{Regions: []string{"ch_be"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Zibelemärit") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Zibelemärit", hols)
		}
	}
}

func TestCH_019_Zibelemärit(t *testing.T) {
	dates := []string{"2020-11-23"}
	opts := holidays.Options{Regions: []string{"ch_be"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Zibelemärit") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Zibelemärit", hols)
		}
	}
}
