// Code generated by gen-holidays from definitions/cl.yaml@v7.0.0. DO NOT EDIT.

package definitions_test

import (
	"testing"

	holidays "github.com/ppeble/go-holidays/pkg"
)

func TestCL_000_AñoNuevo(t *testing.T) {
	dates := []string{"2014-01-01"}
	opts := holidays.Options{Regions: []string{"cl"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Año Nuevo") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Año Nuevo", hols)
		}
	}
}

func TestCL_001_ViernesSanto(t *testing.T) {
	dates := []string{"2011-04-22"}
	opts := holidays.Options{Regions: []string{"cl"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Viernes Santo") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Viernes Santo", hols)
		}
	}
}

func TestCL_002_SábadoSanto(t *testing.T) {
	dates := []string{"2011-04-23"}
	opts := holidays.Options{Regions: []string{"cl"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Sábado Santo") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Sábado Santo", hols)
		}
	}
}

func TestCL_003_ViernesSanto(t *testing.T) {
	dates := []string{"2012-04-06"}
	opts := holidays.Options{Regions: []string{"cl"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Viernes Santo") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Viernes Santo", hols)
		}
	}
}

func TestCL_004_SábadoSanto(t *testing.T) {
	dates := []string{"2012-04-07"}
	opts := holidays.Options{Regions: []string{"cl"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Sábado Santo") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Sábado Santo", hols)
		}
	}
}

func TestCL_005_ViernesSanto(t *testing.T) {
	dates := []string{"2013-03-29"}
	opts := holidays.Options{Regions: []string{"cl"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Viernes Santo") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Viernes Santo", hols)
		}
	}
}

func TestCL_006_SábadoSanto(t *testing.T) {
	dates := []string{"2013-03-30"}
	opts := holidays.Options{Regions: []string{"cl"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Sábado Santo") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Sábado Santo", hols)
		}
	}
}

func TestCL_007_ViernesSanto(t *testing.T) {
	dates := []string{"2014-04-18"}
	opts := holidays.Options{Regions: []string{"cl"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Viernes Santo") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Viernes Santo", hols)
		}
	}
}

func TestCL_008_SábadoSanto(t *testing.T) {
	dates := []string{"2014-04-19"}
	opts := holidays.Options{Regions: []string{"cl"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Sábado Santo") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Sábado Santo", hols)
		}
	}
}

func TestCL_009_ViernesSanto(t *testing.T) {
	dates := []string{"2015-04-03"}
	opts := holidays.Options{Regions: []string{"cl"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Viernes Santo") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Viernes Santo", hols)
		}
	}
}

func TestCL_010_SábadoSanto(t *testing.T) {
	dates := []string{"2015-04-04"}
	opts := holidays.Options{Regions: []string{"cl"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Sábado Santo") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Sábado Santo", hols)
		}
	}
}

func TestCL_011_ViernesSanto(t *testing.T) {
	dates := []string{"2016-03-25"}
	opts := holidays.Options{Regions: []string{"cl"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Viernes Santo") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Viernes Santo", hols)
		}
	}
}

func TestCL_012_SábadoSanto(t *testing.T) {
	dates := []string{"2016-03-26"}
	opts := holidays.Options{Regions: []string{"cl"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Sábado Santo") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Sábado Santo", hols)
		}
	}
}

func TestCL_013_DíaDelTrabajo(t *testing.T) {
	dates := []string{"2014-05-01"}
	opts := holidays.Options{Regions: []string{"cl"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Día del Trabajo") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día del Trabajo", hols)
		}
	}
}

func TestCL_014_DíaDeLasGloriasNavales(t *testing.T) {
	dates := []string{"2014-05-21"}
	opts := holidays.Options{Regions: []string{"cl"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Día de las Glorias Navales") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de las Glorias Navales", hols)
		}
	}
}

func TestCL_015_SanPedroYSanPablo(t *testing.T) {
	dates := []string{"1999-06-29"}
	opts := holidays.Options{Regions: []string{"cl"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "San Pedro y San Pablo") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "San Pedro y San Pablo", hols)
		}
	}
}

func TestCL_016_SanPedroYSanPablo(t *testing.T) {
	dates := []string{"2000-06-26"}
	opts := holidays.Options{Regions: []string{"cl"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "San Pedro y San Pablo") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "San Pedro y San Pablo", hols)
		}
	}
}

func TestCL_017_SanPedroYSanPablo(t *testing.T) {
	dates := []string{"2017-06-26"}
	opts := holidays.Options{Regions: []string{"cl"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "San Pedro y San Pablo") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "San Pedro y San Pablo", hols)
		}
	}
}

func TestCL_018_SanPedroYSanPablo(t *testing.T) {
	dates := []string{"2018-07-2"}
	opts := holidays.Options{Regions: []string{"cl"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "San Pedro y San Pablo") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "San Pedro y San Pablo", hols)
		}
	}
}

func TestCL_019_DíaDeLaVirgenDelCarmen(t *testing.T) {
	dates := []string{"2014-07-16"}
	opts := holidays.Options{Regions: []string{"cl"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Día de la Virgen del Carmen") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de la Virgen del Carmen", hols)
		}
	}
}

func TestCL_020_AsunciónDeLaVirgen(t *testing.T) {
	dates := []string{"2014-08-15"}
	opts := holidays.Options{Regions: []string{"cl"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Asunción de la Virgen") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Asunción de la Virgen", hols)
		}
	}
}

func TestCL_021_IndependenciaNacional(t *testing.T) {
	dates := []string{"2014-09-18"}
	opts := holidays.Options{Regions: []string{"cl"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Independencia Nacional") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Independencia Nacional", hols)
		}
	}
}

func TestCL_022_DíaDeLasGloriasDelEjército(t *testing.T) {
	dates := []string{"2014-09-19"}
	opts := holidays.Options{Regions: []string{"cl"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Día de las Glorias del Ejército") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de las Glorias del Ejército", hols)
		}
	}
}

func TestCL_023_EncuentroDeDosMundos(t *testing.T) {
	dates := []string{"1999-10-12"}
	opts := holidays.Options{Regions: []string{"cl"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Encuentro de Dos Mundos") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Encuentro de Dos Mundos", hols)
		}
	}
}

func TestCL_024_EncuentroDeDosMundos(t *testing.T) {
	dates := []string{"2017-10-9"}
	opts := holidays.Options{Regions: []string{"cl"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Encuentro de Dos Mundos") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Encuentro de Dos Mundos", hols)
		}
	}
}

func TestCL_025_DíaDeLasIglesiasEvangélicasYProtestantes(t *testing.T) {
	dates := []string{"2017-10-27"}
	opts := holidays.Options{Regions: []string{"cl"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Día de las Iglesias Evangélicas y Protestantes") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de las Iglesias Evangélicas y Protestantes", hols)
		}
	}
}

func TestCL_026_DíaDeTodosLosSantos(t *testing.T) {
	dates := []string{"2014-11-01"}
	opts := holidays.Options{Regions: []string{"cl"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Día de Todos los Santos") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de Todos los Santos", hols)
		}
	}
}

func TestCL_027_InmaculadaConcepciónDeMaría(t *testing.T) {
	dates := []string{"2014-12-08"}
	opts := holidays.Options{Regions: []string{"cl"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Inmaculada Concepción de María") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Inmaculada Concepción de María", hols)
		}
	}
}

func TestCL_028_Navidad(t *testing.T) {
	dates := []string{"2014-12-25"}
	opts := holidays.Options{Regions: []string{"cl"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Navidad") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Navidad", hols)
		}
	}
}
