// Code generated by gen-holidays from definitions/co.yaml@v8.0.1. DO NOT EDIT.

package definitions

import (
	"github.com/ppeble/go-holidays/pkg/definition"
	"github.com/ppeble/go-holidays/pkg/engine"
)

var coRules = []definition.HolidayRule{
	{
		Name:             "Jueves Santo",
		Regions:          []string{"co"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -3,
	},
	{
		Name:             "Viernes Santo",
		Regions:          []string{"co"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -2,
	},
	{
		Name:             "Día de la Ascensión",
		Regions:          []string{"co"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 43,
	},
	{
		Name:             "Corpus Christi",
		Regions:          []string{"co"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 64,
	},
	{
		Name:             "Sagrado Corazón",
		Regions:          []string{"co"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 71,
	},
	{
		Name:    "Año Nuevo",
		Regions: []string{"co"},
		Month:   1,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:         "Día de los Reyes Magos",
		Regions:      []string{"co"},
		Month:        1,
		Wday:         -1,
		Function:     "epiphany",
		FunctionArgs: []string{"year"},
	},
	{
		Name:         "Día de San José",
		Regions:      []string{"co"},
		Month:        3,
		Wday:         -1,
		Function:     "saint_josephs_day",
		FunctionArgs: []string{"year"},
	},
	{
		Name:    "Día del Trabajo",
		Regions: []string{"co"},
		Month:   5,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:         "San Pedro y San Pablo",
		Regions:      []string{"co"},
		Month:        6,
		Wday:         -1,
		Function:     "saint_peter_and_saint_paul",
		FunctionArgs: []string{"year"},
	},
	{
		Name:    "Día de la Independencia",
		Regions: []string{"co"},
		Month:   7,
		Mday:    20,
		Wday:    -1,
	},
	{
		Name:    "Batalla de Boyacá",
		Regions: []string{"co"},
		Month:   8,
		Mday:    7,
		Wday:    -1,
	},
	{
		Name:         "La Asunción de la Virgen",
		Regions:      []string{"co"},
		Month:        8,
		Wday:         -1,
		Function:     "assumption_of_mary",
		FunctionArgs: []string{"year"},
	},
	{
		Name:         "Día de la Raza",
		Regions:      []string{"co"},
		Month:        10,
		Wday:         -1,
		Function:     "columbus_day",
		FunctionArgs: []string{"year"},
	},
	{
		Name:         "Día de Todos los Santos",
		Regions:      []string{"co"},
		Month:        11,
		Wday:         -1,
		Function:     "all_saints_day",
		FunctionArgs: []string{"year"},
	},
	{
		Name:         "Independencia de Cartagena",
		Regions:      []string{"co"},
		Month:        11,
		Wday:         -1,
		Function:     "independence_of_cartagena",
		FunctionArgs: []string{"year"},
	},
	{
		Name:    "Día de la Inmaculada Concepción",
		Regions: []string{"co"},
		Month:   12,
		Mday:    8,
		Wday:    -1,
	},
	{
		Name:    "Navidad",
		Regions: []string{"co"},
		Month:   12,
		Mday:    25,
		Wday:    -1,
	},
}

func init() {
	engine.RegisterCountry("co", coRules)
}
