// Code generated by gen-holidays from definitions/co.yaml@v8.0.0. DO NOT EDIT.

package definitions_test

import (
	"fmt"

	holidays "github.com/ppeble/go-holidays/pkg"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("co", func() {
	DescribeTable("000_AñoNuevo", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Año Nuevo")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Año Nuevo", hols))
	},
		Entry("2014-01-01", "2014-01-01"),
	)

	DescribeTable("001_AñoNuevo", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Año Nuevo")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Año Nuevo", hols))
	},
		Entry("2017-01-01", "2017-01-01"),
	)

	DescribeTable("002_DíaDeLosReyesMagos", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Día de los Reyes Magos")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de los Reyes Magos", hols))
	},
		Entry("2014-01-06", "2014-01-06"),
	)

	DescribeTable("003_DíaDeLosReyesMagos", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Día de los Reyes Magos")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de los Reyes Magos", hols))
	},
		Entry("2015-01-12", "2015-01-12"),
	)

	DescribeTable("004_DíaDeLosReyesMagos", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Día de los Reyes Magos")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de los Reyes Magos", hols))
	},
		Entry("2017-01-09", "2017-01-09"),
	)

	DescribeTable("005_DíaDeSanJosé", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Día de San José")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de San José", hols))
	},
		Entry("2014-03-24", "2014-03-24"),
	)

	DescribeTable("006_DíaDeSanJosé", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Día de San José")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de San José", hols))
	},
		Entry("2017-03-20", "2017-03-20"),
	)

	DescribeTable("007_DíaDeSanJosé", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Día de San José")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de San José", hols))
	},
		Entry("2018-03-19", "2018-03-19"),
	)

	DescribeTable("008_JuevesSanto", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Jueves Santo")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Jueves Santo", hols))
	},
		Entry("2015-04-02", "2015-04-02"),
	)

	DescribeTable("009_JuevesSanto", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Jueves Santo")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Jueves Santo", hols))
	},
		Entry("2017-04-13", "2017-04-13"),
	)

	DescribeTable("010_JuevesSanto", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Jueves Santo")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Jueves Santo", hols))
	},
		Entry("2018-03-29", "2018-03-29"),
	)

	DescribeTable("011_ViernesSanto", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Viernes Santo")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Viernes Santo", hols))
	},
		Entry("2014-04-18", "2014-04-18"),
	)

	DescribeTable("012_ViernesSanto", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Viernes Santo")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Viernes Santo", hols))
	},
		Entry("2016-03-25", "2016-03-25"),
	)

	DescribeTable("013_ViernesSanto", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Viernes Santo")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Viernes Santo", hols))
	},
		Entry("2018-03-30", "2018-03-30"),
	)

	DescribeTable("014_DíaDelTrabajo", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Día del Trabajo")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día del Trabajo", hols))
	},
		Entry("2013-05-01", "2013-05-01"),
	)

	DescribeTable("015_DíaDelTrabajo", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Día del Trabajo")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día del Trabajo", hols))
	},
		Entry("2016-05-01", "2016-05-01"),
	)

	DescribeTable("016_DíaDeLaAscensión", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Día de la Ascensión")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de la Ascensión", hols))
	},
		Entry("2014-06-02", "2014-06-02"),
	)

	DescribeTable("017_DíaDeLaAscensión", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Día de la Ascensión")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de la Ascensión", hols))
	},
		Entry("2016-05-09", "2016-05-09"),
	)

	DescribeTable("018_DíaDeLaAscensión", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Día de la Ascensión")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de la Ascensión", hols))
	},
		Entry("2017-05-29", "2017-05-29"),
	)

	DescribeTable("019_CorpusChristi", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Corpus Christi")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Corpus Christi", hols))
	},
		Entry("2014-06-23", "2014-06-23"),
	)

	DescribeTable("020_CorpusChristi", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Corpus Christi")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Corpus Christi", hols))
	},
		Entry("2016-05-30", "2016-05-30"),
	)

	DescribeTable("021_CorpusChristi", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Corpus Christi")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Corpus Christi", hols))
	},
		Entry("2017-06-19", "2017-06-19"),
	)

	DescribeTable("022_SagradoCorazón", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Sagrado Corazón")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Sagrado Corazón", hols))
	},
		Entry("2014-06-30", "2014-06-30"),
	)

	DescribeTable("023_SagradoCorazón", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Sagrado Corazón")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Sagrado Corazón", hols))
	},
		Entry("2016-06-06", "2016-06-06"),
	)

	DescribeTable("024_SagradoCorazón", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Sagrado Corazón")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Sagrado Corazón", hols))
	},
		Entry("2017-06-26", "2017-06-26"),
	)

	DescribeTable("025_SanPedroYSanPablo", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "San Pedro y San Pablo")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "San Pedro y San Pablo", hols))
	},
		Entry("2016-07-04", "2016-07-04"),
	)

	DescribeTable("026_SanPedroYSanPablo", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "San Pedro y San Pablo")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "San Pedro y San Pablo", hols))
	},
		Entry("2017-07-03", "2017-07-03"),
	)

	DescribeTable("027_DíaDeLaIndependencia", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Día de la Independencia")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de la Independencia", hols))
	},
		Entry("2014-07-20", "2014-07-20"),
	)

	DescribeTable("028_DíaDeLaIndependencia", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Día de la Independencia")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de la Independencia", hols))
	},
		Entry("2016-07-20", "2016-07-20"),
	)

	DescribeTable("029_DíaDeLaIndependencia", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Día de la Independencia")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de la Independencia", hols))
	},
		Entry("2018-07-20", "2018-07-20"),
	)

	DescribeTable("030_BatallaDeBoyacá", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Batalla de Boyacá")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Batalla de Boyacá", hols))
	},
		Entry("2014-08-07", "2014-08-07"),
	)

	DescribeTable("031_BatallaDeBoyacá", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Batalla de Boyacá")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Batalla de Boyacá", hols))
	},
		Entry("2016-08-07", "2016-08-07"),
	)

	DescribeTable("032_BatallaDeBoyacá", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Batalla de Boyacá")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Batalla de Boyacá", hols))
	},
		Entry("2018-08-07", "2018-08-07"),
	)

	DescribeTable("033_LaAsunciónDeLaVirgen", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "La Asunción de la Virgen")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "La Asunción de la Virgen", hols))
	},
		Entry("2014-08-18", "2014-08-18"),
	)

	DescribeTable("034_LaAsunciónDeLaVirgen", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "La Asunción de la Virgen")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "La Asunción de la Virgen", hols))
	},
		Entry("2016-08-15", "2016-08-15"),
	)

	DescribeTable("035_LaAsunciónDeLaVirgen", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "La Asunción de la Virgen")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "La Asunción de la Virgen", hols))
	},
		Entry("2017-08-21", "2017-08-21"),
	)

	DescribeTable("036_DíaDeLaRaza", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Día de la Raza")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de la Raza", hols))
	},
		Entry("2014-10-13", "2014-10-13"),
	)

	DescribeTable("037_DíaDeLaRaza", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Día de la Raza")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de la Raza", hols))
	},
		Entry("2016-10-17", "2016-10-17"),
	)

	DescribeTable("038_DíaDeLaRaza", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Día de la Raza")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de la Raza", hols))
	},
		Entry("2017-10-16", "2017-10-16"),
	)

	DescribeTable("039_DíaDeTodosLosSantos", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Día de Todos los Santos")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de Todos los Santos", hols))
	},
		Entry("2014-11-03", "2014-11-03"),
	)

	DescribeTable("040_DíaDeTodosLosSantos", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Día de Todos los Santos")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de Todos los Santos", hols))
	},
		Entry("2016-11-07", "2016-11-07"),
	)

	DescribeTable("041_DíaDeTodosLosSantos", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Día de Todos los Santos")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de Todos los Santos", hols))
	},
		Entry("2017-11-06", "2017-11-06"),
	)

	DescribeTable("042_IndependenciaDeCartagena", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Independencia de Cartagena")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Independencia de Cartagena", hols))
	},
		Entry("2014-11-17", "2014-11-17"),
	)

	DescribeTable("043_IndependenciaDeCartagena", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Independencia de Cartagena")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Independencia de Cartagena", hols))
	},
		Entry("2016-11-14", "2016-11-14"),
	)

	DescribeTable("044_IndependenciaDeCartagena", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Independencia de Cartagena")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Independencia de Cartagena", hols))
	},
		Entry("2017-11-13", "2017-11-13"),
	)

	DescribeTable("045_DíaDeLaInmaculadaConcepción", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Día de la Inmaculada Concepción")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de la Inmaculada Concepción", hols))
	},
		Entry("2013-12-08", "2013-12-08"),
	)

	DescribeTable("046_DíaDeLaInmaculadaConcepción", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Día de la Inmaculada Concepción")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de la Inmaculada Concepción", hols))
	},
		Entry("2014-12-08", "2014-12-08"),
	)

	DescribeTable("047_DíaDeLaInmaculadaConcepción", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Día de la Inmaculada Concepción")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de la Inmaculada Concepción", hols))
	},
		Entry("2016-12-08", "2016-12-08"),
	)

	DescribeTable("048_Navidad", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Navidad")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Navidad", hols))
	},
		Entry("2014-12-25", "2014-12-25"),
	)

	DescribeTable("049_Navidad", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Navidad")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Navidad", hols))
	},
		Entry("2016-12-25", "2016-12-25"),
	)

	DescribeTable("050_Navidad", func(s string) {
		opts := holidays.Options{Regions: []string{"co"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Navidad")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Navidad", hols))
	},
		Entry("2017-12-25", "2017-12-25"),
	)

})
