// Code generated by gen-holidays from definitions/cz.yaml@v6.1.1. DO NOT EDIT.

package definitions_test

import (
	"testing"

	holidays "github.com/ppeble/go-holidays/pkg"
)

func TestCZ_000_DenObnovySamostatnéhoČeskéhoStátu(t *testing.T) {
	dates := []string{"2010-01-01"}
	opts := holidays.Options{Regions: []string{"cz"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Den obnovy samostatného českého státu") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Den obnovy samostatného českého státu", hols)
		}
	}
}

func TestCZ_001_VelkýPátek(t *testing.T) {
	dates := []string{"2016-03-25"}
	opts := holidays.Options{Regions: []string{"cz"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Velký pátek") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Velký pátek", hols)
		}
	}
}

func TestCZ_002_VelikonočníPondělí(t *testing.T) {
	dates := []string{"2010-04-05"}
	opts := holidays.Options{Regions: []string{"cz"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Velikonoční pondělí") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Velikonoční pondělí", hols)
		}
	}
}

func TestCZ_003_SvátekPráce(t *testing.T) {
	dates := []string{"2010-05-01"}
	opts := holidays.Options{Regions: []string{"cz"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Svátek práce") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Svátek práce", hols)
		}
	}
}

func TestCZ_004_DenVítězství(t *testing.T) {
	dates := []string{"2010-05-08"}
	opts := holidays.Options{Regions: []string{"cz"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Den vítězství") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Den vítězství", hols)
		}
	}
}

func TestCZ_005_DenSlovanskýchVěrozvěstůCyrilaAMetoděje(t *testing.T) {
	dates := []string{"2010-07-05"}
	opts := holidays.Options{Regions: []string{"cz"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Den slovanských věrozvěstů Cyrila a Metoděje") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Den slovanských věrozvěstů Cyrila a Metoděje", hols)
		}
	}
}

func TestCZ_006_DenUpáleníMistraJanaHusa(t *testing.T) {
	dates := []string{"2010-07-06"}
	opts := holidays.Options{Regions: []string{"cz"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Den upálení mistra Jana Husa") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Den upálení mistra Jana Husa", hols)
		}
	}
}

func TestCZ_007_DenČeskéStátnosti(t *testing.T) {
	dates := []string{"2010-09-28"}
	opts := holidays.Options{Regions: []string{"cz"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Den české státnosti") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Den české státnosti", hols)
		}
	}
}

func TestCZ_008_DenVznikuSamostatnéhoČeskoslovenskéhoStátu(t *testing.T) {
	dates := []string{"2010-10-28"}
	opts := holidays.Options{Regions: []string{"cz"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Den vzniku samostatného československého státu") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Den vzniku samostatného československého státu", hols)
		}
	}
}

func TestCZ_009_DenBojeZaSvoboduADemokracii(t *testing.T) {
	dates := []string{"2010-11-17"}
	opts := holidays.Options{Regions: []string{"cz"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Den boje za svobodu a demokracii") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Den boje za svobodu a demokracii", hols)
		}
	}
}

func TestCZ_010_ŠtědrýDen(t *testing.T) {
	dates := []string{"2010-12-24"}
	opts := holidays.Options{Regions: []string{"cz"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Štědrý den") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Štědrý den", hols)
		}
	}
}

func TestCZ_011_1SvátekVánoční(t *testing.T) {
	dates := []string{"2010-12-25"}
	opts := holidays.Options{Regions: []string{"cz"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "1. svátek vánoční") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "1. svátek vánoční", hols)
		}
	}
}

func TestCZ_012_2SvátekVánoční(t *testing.T) {
	dates := []string{"2010-12-26"}
	opts := holidays.Options{Regions: []string{"cz"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "2. svátek vánoční") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "2. svátek vánoční", hols)
		}
	}
}
