// Code generated by gen-holidays from definitions/de.yaml@v8.0.0. DO NOT EDIT.

package definitions_test

import (
	"testing"

	holidays "github.com/ppeble/go-holidays/pkg"
)

func TestDE_000_Neujahrstag(t *testing.T) {
	dates := []string{"2009-01-01"}
	opts := holidays.Options{Regions: []string{"de"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Neujahrstag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Neujahrstag", hols)
		}
	}
}

func TestDE_001_Karfreitag(t *testing.T) {
	dates := []string{"2009-04-10"}
	opts := holidays.Options{Regions: []string{"de"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Karfreitag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Karfreitag", hols)
		}
	}
}

func TestDE_002_Ostersonntag(t *testing.T) {
	dates := []string{"2009-04-12"}
	opts := holidays.Options{Regions: []string{"de"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Ostersonntag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Ostersonntag", hols)
		}
	}
}

func TestDE_003_Ostermontag(t *testing.T) {
	dates := []string{"2009-04-13"}
	opts := holidays.Options{Regions: []string{"de"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Ostermontag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Ostermontag", hols)
		}
	}
}

func TestDE_004_TagDerArbeit(t *testing.T) {
	dates := []string{"2009-05-01"}
	opts := holidays.Options{Regions: []string{"de"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Tag der Arbeit") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Tag der Arbeit", hols)
		}
	}
}

func TestDE_005_ChristiHimmelfahrt(t *testing.T) {
	dates := []string{"2009-05-21"}
	opts := holidays.Options{Regions: []string{"de"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Christi Himmelfahrt") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christi Himmelfahrt", hols)
		}
	}
}

func TestDE_006_Pfingstsonntag(t *testing.T) {
	dates := []string{"2009-05-31"}
	opts := holidays.Options{Regions: []string{"de"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Pfingstsonntag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Pfingstsonntag", hols)
		}
	}
}

func TestDE_007_Pfingstmontag(t *testing.T) {
	dates := []string{"2009-06-01"}
	opts := holidays.Options{Regions: []string{"de"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Pfingstmontag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Pfingstmontag", hols)
		}
	}
}

func TestDE_008_TagDerDeutschenEinheit(t *testing.T) {
	dates := []string{"2009-10-03"}
	opts := holidays.Options{Regions: []string{"de"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Tag der Deutschen Einheit") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Tag der Deutschen Einheit", hols)
		}
	}
}

func TestDE_009_HeiligAbend(t *testing.T) {
	dates := []string{"2009-12-24"}
	opts := holidays.Options{Regions: []string{"de"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Heilig Abend") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Heilig Abend", hols)
		}
	}
}

func TestDE_010_1Weihnachtstag(t *testing.T) {
	dates := []string{"2009-12-25"}
	opts := holidays.Options{Regions: []string{"de"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "1. Weihnachtstag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "1. Weihnachtstag", hols)
		}
	}
}

func TestDE_011_2Weihnachtstag(t *testing.T) {
	dates := []string{"2009-12-26"}
	opts := holidays.Options{Regions: []string{"de"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "2. Weihnachtstag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "2. Weihnachtstag", hols)
		}
	}
}

func TestDE_012_Silvester(t *testing.T) {
	dates := []string{"2009-12-31"}
	opts := holidays.Options{Regions: []string{"de"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Silvester") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Silvester", hols)
		}
	}
}

func TestDE_013_HeiligeDreiKönige(t *testing.T) {
	dates := []string{"2009-01-06"}
	opts := holidays.Options{Regions: []string{"de_bw", "de_by", "de_st", "de_"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Heilige Drei Könige") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Heilige Drei Könige", hols)
		}
	}
}

func TestDE_014_Fronleichnam(t *testing.T) {
	dates := []string{"2009-06-11"}
	opts := holidays.Options{Regions: []string{"de_bw", "de_by", "de_he", "de_nw", "de_rp", "de_sl", "de_sn_sorbian", "de_th_cath"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Fronleichnam") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Fronleichnam", hols)
		}
	}
}

func TestDE_015_MariäHimmelfahrt(t *testing.T) {
	dates := []string{"2009-08-15"}
	opts := holidays.Options{Regions: []string{"de_by", "de_sl", "de_"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Mariä Himmelfahrt") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Mariä Himmelfahrt", hols)
		}
	}
}

func TestDE_016_Reformationstag(t *testing.T) {
	dates := []string{"2009-10-31"}
	opts := holidays.Options{Regions: []string{"de_bb", "de_mv", "de_sn", "de_st", "de_th", "de_"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Reformationstag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Reformationstag", hols)
		}
	}
}

func TestDE_017_Reformationstag(t *testing.T) {
	dates := []string{"2009-10-31"}
	opts := holidays.Options{Regions: []string{"de_bw"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Reformationstag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Reformationstag", hols)
		}
	}
}

func TestDE_018_Reformationstag(t *testing.T) {
	dates := []string{"2017-10-31"}
	opts := holidays.Options{Regions: []string{"de"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Reformationstag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Reformationstag", hols)
		}
	}
}

func TestDE_019_Negative(t *testing.T) {
	dates := []string{"2016-10-31"}
	opts := holidays.Options{Regions: []string{"de"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if len(hols) > 0 {
			t.Errorf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols)
		}
	}
}

func TestDE_020_Negative(t *testing.T) {
	dates := []string{"2018-10-31"}
	opts := holidays.Options{Regions: []string{"de"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if len(hols) > 0 {
			t.Errorf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols)
		}
	}
}

func TestDE_021_Reformationstag(t *testing.T) {
	dates := []string{"2018-10-31"}
	opts := holidays.Options{Regions: []string{"de_bb", "de_hb", "de_hh", "de_mv", "de_ni", "de_sh", "de_sn", "de_st", "de_th"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Reformationstag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Reformationstag", hols)
		}
	}
}

func TestDE_022_Allerheiligen(t *testing.T) {
	dates := []string{"2009-11-01"}
	opts := holidays.Options{Regions: []string{"de_bw", "de_by", "de_nw", "de_rp", "de_sl", "de_"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Allerheiligen") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Allerheiligen", hols)
		}
	}
}

func TestDE_023_Friedensfest(t *testing.T) {
	dates := []string{"2015-08-08"}
	opts := holidays.Options{Regions: []string{"de_by_augsburg"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Friedensfest") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Friedensfest", hols)
		}
	}
}

func TestDE_024_Negative(t *testing.T) {
	dates := []string{"2015-08-08"}
	opts := holidays.Options{Regions: []string{"de", "de_bw", "de_by", "de_bb", "de_he", "de_mv", "de_nw", "de_rp", "de_sl", "de_sn", "de_st", "de_th"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if len(hols) > 0 {
			t.Errorf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols)
		}
	}
}

func TestDE_025_Negative(t *testing.T) {
	dates := []string{"2010-05-08"}
	opts := holidays.Options{Regions: []string{"de"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if len(hols) > 0 {
			t.Errorf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols)
		}
	}
}

func TestDE_026_Negative(t *testing.T) {
	dates := []string{"2010-08-08"}
	opts := holidays.Options{Regions: []string{"de"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if len(hols) > 0 {
			t.Errorf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols)
		}
	}
}

func TestDE_027_BußUndBettag(t *testing.T) {
	dates := []string{"2004-11-17"}
	opts := holidays.Options{Regions: []string{"de_sn"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Buß- und Bettag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Buß- und Bettag", hols)
		}
	}
}

func TestDE_028_BußUndBettag(t *testing.T) {
	dates := []string{"2005-11-16"}
	opts := holidays.Options{Regions: []string{"de_sn"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Buß- und Bettag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Buß- und Bettag", hols)
		}
	}
}

func TestDE_029_BußUndBettag(t *testing.T) {
	dates := []string{"2006-11-22"}
	opts := holidays.Options{Regions: []string{"de_sn"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Buß- und Bettag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Buß- und Bettag", hols)
		}
	}
}

func TestDE_030_BußUndBettag(t *testing.T) {
	dates := []string{"2009-11-18"}
	opts := holidays.Options{Regions: []string{"de_sn"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Buß- und Bettag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Buß- und Bettag", hols)
		}
	}
}

func TestDE_031_Weiberfastnacht(t *testing.T) {
	dates := []string{"2016-02-04"}
	opts := holidays.Options{Regions: []string{"de_bw", "de_by", "de_he", "de_nw", "de_rp", "de_sl", "de_sn"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Weiberfastnacht") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Weiberfastnacht", hols)
		}
	}
}

func TestDE_032_Rosenmontag(t *testing.T) {
	dates := []string{"2016-02-08"}
	opts := holidays.Options{Regions: []string{"de_bw", "de_by", "de_he", "de_nw", "de_rp", "de_sl", "de_sn"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Rosenmontag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Rosenmontag", hols)
		}
	}
}

func TestDE_033_Aschermittwoch(t *testing.T) {
	dates := []string{"2016-02-10"}
	opts := holidays.Options{Regions: []string{"de_bw", "de_by", "de_he", "de_nw", "de_rp", "de_sl", "de_sn"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Aschermittwoch") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Aschermittwoch", hols)
		}
	}
}

func TestDE_034_Negative(t *testing.T) {
	dates := []string{"2018-03-08"}
	opts := holidays.Options{Regions: []string{"de_be"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if len(hols) > 0 {
			t.Errorf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols)
		}
	}
}

func TestDE_035_InternationalerFrauentag(t *testing.T) {
	dates := []string{"2019-03-08"}
	opts := holidays.Options{Regions: []string{"de_be"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Internationaler Frauentag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Internationaler Frauentag", hols)
		}
	}
}

func TestDE_036_InternationalerFrauentag(t *testing.T) {
	dates := []string{"2023-03-08"}
	opts := holidays.Options{Regions: []string{"de_mv"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Internationaler Frauentag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Internationaler Frauentag", hols)
		}
	}
}

func TestDE_037_TagDerBefreiung(t *testing.T) {
	dates := []string{"2020-05-08"}
	opts := holidays.Options{Regions: []string{"de_be"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Tag der Befreiung") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Tag der Befreiung", hols)
		}
	}
}

func TestDE_038_JahrestagDesVolksaufstandsInDerDDR(t *testing.T) {
	dates := []string{"2028-06-17"}
	opts := holidays.Options{Regions: []string{"de_be"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Jahrestag des Volksaufstands in der DDR") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Jahrestag des Volksaufstands in der DDR", hols)
		}
	}
}

func TestDE_039_Weltkindertag(t *testing.T) {
	dates := []string{"2024-09-20"}
	opts := holidays.Options{Regions: []string{"de_th"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Weltkindertag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Weltkindertag", hols)
		}
	}
}
