// Code generated by gen-holidays from definitions/dk.yaml@v8.0.0. DO NOT EDIT.

package definitions_test

import (
	"testing"

	holidays "github.com/ppeble/go-holidays/pkg"
)

func TestDK_000_StoreBededag(t *testing.T) {
	dates := []string{"2023-05-05"}
	opts := holidays.Options{Regions: []string{"dk"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Store Bededag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Store Bededag", hols)
		}
	}
}

func TestDK_001_Negative(t *testing.T) {
	dates := []string{"2024-04-26"}
	opts := holidays.Options{Regions: []string{"dk"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if len(hols) > 0 {
			t.Errorf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols)
		}
	}
}

func TestDK_002_Nytårsdag(t *testing.T) {
	dates := []string{"2007-01-01"}
	opts := holidays.Options{Regions: []string{"dk"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Nytårsdag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Nytårsdag", hols)
		}
	}
}

func TestDK_003_Fastelavn(t *testing.T) {
	dates := []string{"2007-02-18"}
	opts := holidays.Options{Regions: []string{"dk"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Fastelavn") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Fastelavn", hols)
		}
	}
}

func TestDK_004_2Påskedag(t *testing.T) {
	dates := []string{"2007-04-09"}
	opts := holidays.Options{Regions: []string{"dk"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "2. påskedag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "2. påskedag", hols)
		}
	}
}

func TestDK_005_DronningensFødselsdag(t *testing.T) {
	dates := []string{"2007-04-16"}
	opts := holidays.Options{Regions: []string{"dk"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Dronningens fødselsdag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Dronningens fødselsdag", hols)
		}
	}
}

func TestDK_006_Skærtorsdag(t *testing.T) {
	dates := []string{"2007-04-05"}
	opts := holidays.Options{Regions: []string{"dk"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Skærtorsdag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Skærtorsdag", hols)
		}
	}
}

func TestDK_007_Langfredag(t *testing.T) {
	dates := []string{"2007-04-06"}
	opts := holidays.Options{Regions: []string{"dk"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Langfredag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Langfredag", hols)
		}
	}
}

func TestDK_008_Påskedag(t *testing.T) {
	dates := []string{"2007-04-08"}
	opts := holidays.Options{Regions: []string{"dk"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Påskedag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Påskedag", hols)
		}
	}
}

func TestDK_009_ArbejdernesKampdag(t *testing.T) {
	dates := []string{"2007-05-01"}
	opts := holidays.Options{Regions: []string{"dk"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Arbejdernes kampdag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Arbejdernes kampdag", hols)
		}
	}
}

func TestDK_010_StoreBededag(t *testing.T) {
	dates := []string{"2007-05-04"}
	opts := holidays.Options{Regions: []string{"dk"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Store Bededag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Store Bededag", hols)
		}
	}
}

func TestDK_011_KristiHimmelfartsdag(t *testing.T) {
	dates := []string{"2007-05-17"}
	opts := holidays.Options{Regions: []string{"dk"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Kristi Himmelfartsdag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Kristi Himmelfartsdag", hols)
		}
	}
}

func TestDK_012_Pinsedag(t *testing.T) {
	dates := []string{"2007-05-27"}
	opts := holidays.Options{Regions: []string{"dk"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Pinsedag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Pinsedag", hols)
		}
	}
}

func TestDK_013_2Pinsedag(t *testing.T) {
	dates := []string{"2007-05-28"}
	opts := holidays.Options{Regions: []string{"dk"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "2. Pinsedag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "2. Pinsedag", hols)
		}
	}
}

func TestDK_014_Grundlovsdag(t *testing.T) {
	dates := []string{"2007-06-05"}
	opts := holidays.Options{Regions: []string{"dk"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Grundlovsdag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Grundlovsdag", hols)
		}
	}
}

func TestDK_015_Juleaftensdag(t *testing.T) {
	dates := []string{"2007-12-24"}
	opts := holidays.Options{Regions: []string{"dk"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Juleaftensdag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Juleaftensdag", hols)
		}
	}
}

func TestDK_016_1Juledag(t *testing.T) {
	dates := []string{"2007-12-25"}
	opts := holidays.Options{Regions: []string{"dk"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "1. juledag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "1. juledag", hols)
		}
	}
}

func TestDK_017_2Juledag(t *testing.T) {
	dates := []string{"2007-12-26"}
	opts := holidays.Options{Regions: []string{"dk"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "2. juledag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "2. juledag", hols)
		}
	}
}
