// Code generated by gen-holidays from definitions/fi.yaml@v7.0.0. DO NOT EDIT.

package definitions_test

import (
	"testing"

	holidays "github.com/ppeble/go-holidays/pkg"
)

func TestFI_000_Uudenvuodenpäivä(t *testing.T) {
	dates := []string{"2008-01-01"}
	opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Uudenvuodenpäivä") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Uudenvuodenpäivä", hols)
		}
	}
}

func TestFI_001_Loppiainen(t *testing.T) {
	dates := []string{"2008-01-06"}
	opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Loppiainen") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Loppiainen", hols)
		}
	}
}

func TestFI_002_Pitkäperjantai(t *testing.T) {
	dates := []string{"2008-03-21"}
	opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Pitkäperjantai") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Pitkäperjantai", hols)
		}
	}
}

func TestFI_003_Pääsiäispäivä(t *testing.T) {
	dates := []string{"2008-03-23"}
	opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Pääsiäispäivä") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Pääsiäispäivä", hols)
		}
	}
}

func TestFI_004_2Pääsiäispäivä(t *testing.T) {
	dates := []string{"2008-03-24"}
	opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "2. Pääsiäispäivä") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "2. Pääsiäispäivä", hols)
		}
	}
}

func TestFI_005_Helatorstai(t *testing.T) {
	dates := []string{"2008-05-01"}
	opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Helatorstai") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Helatorstai", hols)
		}
	}
}

func TestFI_006_Helluntaipäivä(t *testing.T) {
	dates := []string{"2008-05-11"}
	opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Helluntaipäivä") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Helluntaipäivä", hols)
		}
	}
}

func TestFI_007_Juhannusaatto(t *testing.T) {
	dates := []string{"2009-06-19"}
	opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Juhannusaatto") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Juhannusaatto", hols)
		}
	}
}

func TestFI_008_Juhannusaatto(t *testing.T) {
	dates := []string{"2010-06-25"}
	opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Juhannusaatto") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Juhannusaatto", hols)
		}
	}
}

func TestFI_009_Juhannusaatto(t *testing.T) {
	dates := []string{"2011-06-24"}
	opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Juhannusaatto") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Juhannusaatto", hols)
		}
	}
}

func TestFI_010_Juhannusaatto(t *testing.T) {
	dates := []string{"2012-06-22"}
	opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Juhannusaatto") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Juhannusaatto", hols)
		}
	}
}

func TestFI_011_Juhannusaatto(t *testing.T) {
	dates := []string{"2013-06-21"}
	opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Juhannusaatto") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Juhannusaatto", hols)
		}
	}
}

func TestFI_012_Juhannuspäivä(t *testing.T) {
	dates := []string{"2005-06-25"}
	opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Juhannuspäivä") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Juhannuspäivä", hols)
		}
	}
}

func TestFI_013_Juhannuspäivä(t *testing.T) {
	dates := []string{"2006-06-24"}
	opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Juhannuspäivä") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Juhannuspäivä", hols)
		}
	}
}

func TestFI_014_Juhannuspäivä(t *testing.T) {
	dates := []string{"2007-06-23"}
	opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Juhannuspäivä") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Juhannuspäivä", hols)
		}
	}
}

func TestFI_015_Juhannuspäivä(t *testing.T) {
	dates := []string{"2008-06-21"}
	opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Juhannuspäivä") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Juhannuspäivä", hols)
		}
	}
}

func TestFI_016_Pyhäinpäivä(t *testing.T) {
	dates := []string{"2005-11-05"}
	opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Pyhäinpäivä") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Pyhäinpäivä", hols)
		}
	}
}

func TestFI_017_Pyhäinpäivä(t *testing.T) {
	dates := []string{"2006-11-04"}
	opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Pyhäinpäivä") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Pyhäinpäivä", hols)
		}
	}
}

func TestFI_018_Pyhäinpäivä(t *testing.T) {
	dates := []string{"2007-11-03"}
	opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Pyhäinpäivä") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Pyhäinpäivä", hols)
		}
	}
}

func TestFI_019_Pyhäinpäivä(t *testing.T) {
	dates := []string{"2008-11-01"}
	opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Pyhäinpäivä") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Pyhäinpäivä", hols)
		}
	}
}

func TestFI_020_Itsenäisyyspäivä(t *testing.T) {
	dates := []string{"2008-12-06"}
	opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Itsenäisyyspäivä") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Itsenäisyyspäivä", hols)
		}
	}
}

func TestFI_021_Jouluaatto(t *testing.T) {
	dates := []string{"2008-12-24"}
	opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Jouluaatto") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Jouluaatto", hols)
		}
	}
}

func TestFI_022_Joulupäivä(t *testing.T) {
	dates := []string{"2008-12-25"}
	opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Joulupäivä") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Joulupäivä", hols)
		}
	}
}

func TestFI_023_Tapaninpäivä(t *testing.T) {
	dates := []string{"2008-12-26"}
	opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Tapaninpäivä") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Tapaninpäivä", hols)
		}
	}
}
