// Code generated by gen-holidays from definitions/fr.yaml@v6.1.1. DO NOT EDIT.

package definitions_test

import (
	"testing"

	holidays "github.com/ppeble/go-holidays/pkg"
)

func TestFR_000_JourDeLAn(t *testing.T) {
	dates := []string{"2007-01-01"}
	opts := holidays.Options{Regions: []string{"fr"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Jour de l'an") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Jour de l'an", hols)
		}
	}
}

func TestFR_001_LundiDePâques(t *testing.T) {
	dates := []string{"2007-04-09"}
	opts := holidays.Options{Regions: []string{"fr"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Lundi de Pâques") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Lundi de Pâques", hols)
		}
	}
}

func TestFR_002_FêteDuTravail(t *testing.T) {
	dates := []string{"2007-05-01"}
	opts := holidays.Options{Regions: []string{"fr"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Fête du travail") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Fête du travail", hols)
		}
	}
}

func TestFR_003_Victoire1945(t *testing.T) {
	dates := []string{"2007-05-08"}
	opts := holidays.Options{Regions: []string{"fr"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Victoire 1945") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Victoire 1945", hols)
		}
	}
}

func TestFR_004_Ascension(t *testing.T) {
	dates := []string{"2007-05-17"}
	opts := holidays.Options{Regions: []string{"fr"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Ascension") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Ascension", hols)
		}
	}
}

func TestFR_005_Negative(t *testing.T) {
	dates := []string{"2007-05-27"}
	opts := holidays.Options{Regions: []string{"fr"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if len(hols) > 0 {
			t.Errorf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols)
		}
	}
}

func TestFR_006_FêteNationale(t *testing.T) {
	dates := []string{"2007-07-14"}
	opts := holidays.Options{Regions: []string{"fr"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Fête nationale") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Fête nationale", hols)
		}
	}
}

func TestFR_007_Assomption(t *testing.T) {
	dates := []string{"2007-08-15"}
	opts := holidays.Options{Regions: []string{"fr"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Assomption") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Assomption", hols)
		}
	}
}

func TestFR_008_Toussaint(t *testing.T) {
	dates := []string{"2007-11-01"}
	opts := holidays.Options{Regions: []string{"fr"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Toussaint") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Toussaint", hols)
		}
	}
}

func TestFR_009_Armistice1918(t *testing.T) {
	dates := []string{"2007-11-11"}
	opts := holidays.Options{Regions: []string{"fr"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Armistice 1918") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Armistice 1918", hols)
		}
	}
}

func TestFR_010_Noël(t *testing.T) {
	dates := []string{"2007-12-25"}
	opts := holidays.Options{Regions: []string{"fr"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Noël") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Noël", hols)
		}
	}
}

func TestFR_011_Negative(t *testing.T) {
	dates := []string{"2007-04-08"}
	opts := holidays.Options{Regions: []string{"fr"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if len(hols) > 0 {
			t.Errorf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols)
		}
	}
}

func TestFR_012_LundiDePentecôte(t *testing.T) {
	dates := []string{"2007-05-28"}
	opts := holidays.Options{Regions: []string{"fr"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Lundi de Pentecôte") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Lundi de Pentecôte", hols)
		}
	}
}

func TestFR_013_Pâques(t *testing.T) {
	dates := []string{"2007-04-08"}
	opts := holidays.Options{Regions: []string{"fr"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Pâques") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Pâques", hols)
		}
	}
}

func TestFR_014_Pentecôte(t *testing.T) {
	dates := []string{"2007-05-27"}
	opts := holidays.Options{Regions: []string{"fr"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Pentecôte") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Pentecôte", hols)
		}
	}
}

func TestFR_015_SaintÉtienne(t *testing.T) {
	dates := []string{"2017-12-26"}
	opts := holidays.Options{Regions: []string{"fr_a", "fr_m"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Saint-Étienne") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Saint-Étienne", hols)
		}
	}
}
