// Code generated by gen-holidays. DO NOT EDIT.

package definitions_test

import (
	"time"

	holidays "github.com/ppeble/go-holidays/pkg"
	_ "github.com/ppeble/go-holidays/pkg/definitions"
)

func parseFlex(s string) (time.Time, error) {
	return time.Parse("2006-1-2", s)
}

func hasNamed(hs []holidays.Holiday, name string) bool {
	for _, h := range hs {
		if h.Name == name {
			return true
		}
	}
	return false
}
