// Code generated by gen-holidays from definitions/hk.yaml@v7.0.0. DO NOT EDIT.

package definitions_test

import (
	"testing"

	holidays "github.com/ppeble/go-holidays/pkg"
)

func TestHK_000_NewYearSDay(t *testing.T) {
	dates := []string{"2016-01-01"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "New Year's Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols)
		}
	}
}

func TestHK_001_LunarNewYearSDay(t *testing.T) {
	dates := []string{"2016-02-08"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Lunar New Year's Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Lunar New Year's Day", hols)
		}
	}
}

func TestHK_002_TheSecondDayOfLunarNewYear(t *testing.T) {
	dates := []string{"2016-02-09"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "The second day of Lunar New Year") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "The second day of Lunar New Year", hols)
		}
	}
}

func TestHK_003_TheThirdDayOfLunarNewYear(t *testing.T) {
	dates := []string{"2016-02-10"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "The third day of Lunar New Year") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "The third day of Lunar New Year", hols)
		}
	}
}

func TestHK_004_GoodFriday(t *testing.T) {
	dates := []string{"2016-03-25"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Good Friday") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Good Friday", hols)
		}
	}
}

func TestHK_005_TheDayFollowingGoodFriday(t *testing.T) {
	dates := []string{"2016-03-26"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "The day following Good Friday") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "The day following Good Friday", hols)
		}
	}
}

func TestHK_006_EasterMonday(t *testing.T) {
	dates := []string{"2016-03-28"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Easter Monday") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Easter Monday", hols)
		}
	}
}

func TestHK_007_LabourDay(t *testing.T) {
	dates := []string{"2016-05-02"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Labour Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Labour Day", hols)
		}
	}
}

func TestHK_008_HongKongSpecialAdministrativeRegionEstablishmentDay(t *testing.T) {
	dates := []string{"2016-07-01"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Hong Kong Special Administrative Region Establishment Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Hong Kong Special Administrative Region Establishment Day", hols)
		}
	}
}

func TestHK_009_NationalDay(t *testing.T) {
	dates := []string{"2016-10-01"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "National Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "National Day", hols)
		}
	}
}

func TestHK_010_ChristmasDay(t *testing.T) {
	dates := []string{"2016-12-26"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Christmas Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols)
		}
	}
}

func TestHK_011_BoxingDay(t *testing.T) {
	dates := []string{"2016-12-27"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Boxing Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Boxing Day", hols)
		}
	}
}

func TestHK_012_NewYearSDay(t *testing.T) {
	dates := []string{"2017-01-02"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "New Year's Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols)
		}
	}
}

func TestHK_013_LunarNewYearSDay(t *testing.T) {
	dates := []string{"2017-01-28"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Lunar New Year's Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Lunar New Year's Day", hols)
		}
	}
}

func TestHK_014_TheSecondDayOfLunarNewYear(t *testing.T) {
	dates := []string{"2017-01-30"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "The second day of Lunar New Year") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "The second day of Lunar New Year", hols)
		}
	}
}

func TestHK_015_TheThirdDayOfLunarNewYear(t *testing.T) {
	dates := []string{"2017-01-31"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "The third day of Lunar New Year") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "The third day of Lunar New Year", hols)
		}
	}
}

func TestHK_016_GoodFriday(t *testing.T) {
	dates := []string{"2017-04-14"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Good Friday") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Good Friday", hols)
		}
	}
}

func TestHK_017_TheDayFollowingGoodFriday(t *testing.T) {
	dates := []string{"2017-04-15"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "The day following Good Friday") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "The day following Good Friday", hols)
		}
	}
}

func TestHK_018_EasterMonday(t *testing.T) {
	dates := []string{"2017-04-17"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Easter Monday") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Easter Monday", hols)
		}
	}
}

func TestHK_019_LabourDay(t *testing.T) {
	dates := []string{"2017-05-01"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Labour Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Labour Day", hols)
		}
	}
}

func TestHK_020_HongKongSpecialAdministrativeRegionEstablishmentDay(t *testing.T) {
	dates := []string{"2017-07-01"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Hong Kong Special Administrative Region Establishment Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Hong Kong Special Administrative Region Establishment Day", hols)
		}
	}
}

func TestHK_021_NationalDay(t *testing.T) {
	dates := []string{"2017-10-02"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "National Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "National Day", hols)
		}
	}
}

func TestHK_022_ChristmasDay(t *testing.T) {
	dates := []string{"2017-12-25"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Christmas Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols)
		}
	}
}

func TestHK_023_BoxingDay(t *testing.T) {
	dates := []string{"2017-12-26"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Boxing Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Boxing Day", hols)
		}
	}
}

func TestHK_024_NewYearSDay(t *testing.T) {
	dates := []string{"2023-01-02"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "New Year's Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols)
		}
	}
}

func TestHK_025_LunarNewYearSDay(t *testing.T) {
	dates := []string{"2023-01-23"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Lunar New Year's Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Lunar New Year's Day", hols)
		}
	}
}

func TestHK_026_TheSecondDayOfLunarNewYear(t *testing.T) {
	dates := []string{"2023-01-24"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "The second day of Lunar New Year") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "The second day of Lunar New Year", hols)
		}
	}
}

func TestHK_027_TheThirdDayOfLunarNewYear(t *testing.T) {
	dates := []string{"2023-01-25"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "The third day of Lunar New Year") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "The third day of Lunar New Year", hols)
		}
	}
}

func TestHK_028_ChingMingFestival(t *testing.T) {
	dates := []string{"2023-04-05"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Ching Ming Festival") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Ching Ming Festival", hols)
		}
	}
}

func TestHK_029_GoodFriday(t *testing.T) {
	dates := []string{"2023-04-07"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Good Friday") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Good Friday", hols)
		}
	}
}

func TestHK_030_TheDayFollowingGoodFriday(t *testing.T) {
	dates := []string{"2023-04-08"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "The day following Good Friday") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "The day following Good Friday", hols)
		}
	}
}

func TestHK_031_EasterMonday(t *testing.T) {
	dates := []string{"2023-04-10"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Easter Monday") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Easter Monday", hols)
		}
	}
}

func TestHK_032_LabourDay(t *testing.T) {
	dates := []string{"2023-05-01"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Labour Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Labour Day", hols)
		}
	}
}

func TestHK_033_BuddhaSBirthday(t *testing.T) {
	dates := []string{"2023-05-26"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Buddha's Birthday") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Buddha's Birthday", hols)
		}
	}
}

func TestHK_034_TuenNgFestival(t *testing.T) {
	dates := []string{"2023-06-22"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Tuen Ng Festival") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Tuen Ng Festival", hols)
		}
	}
}

func TestHK_035_HongKongSpecialAdministrativeRegionEstablishmentDay(t *testing.T) {
	dates := []string{"2023-07-01"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Hong Kong Special Administrative Region Establishment Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Hong Kong Special Administrative Region Establishment Day", hols)
		}
	}
}

func TestHK_036_TheDayFollowingTheChineseMidAutumnFestival(t *testing.T) {
	dates := []string{"2023-09-30"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "The day following the Chinese Mid-Autumn Festival") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "The day following the Chinese Mid-Autumn Festival", hols)
		}
	}
}

func TestHK_037_NationalDay(t *testing.T) {
	dates := []string{"2023-10-02"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "National Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "National Day", hols)
		}
	}
}

func TestHK_038_ChungYeungFestival(t *testing.T) {
	dates := []string{"2023-10-23"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Chung Yeung Festival") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Chung Yeung Festival", hols)
		}
	}
}

func TestHK_039_ChristmasDay(t *testing.T) {
	dates := []string{"2023-12-25"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Christmas Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols)
		}
	}
}

func TestHK_040_BoxingDay(t *testing.T) {
	dates := []string{"2023-12-26"}
	opts := holidays.Options{Regions: []string{"hk"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Boxing Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Boxing Day", hols)
		}
	}
}
