// Code generated by gen-holidays from definitions/ie.yaml@v7.0.0. DO NOT EDIT.

package definitions_test

import (
	"testing"

	holidays "github.com/ppeble/go-holidays/pkg"
)

func TestIE_000_NewYearSDay(t *testing.T) {
	dates := []string{"2008-01-01"}
	opts := holidays.Options{Regions: []string{"ie"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "New Year's Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols)
		}
	}
}

func TestIE_001_StPatrickSDay(t *testing.T) {
	dates := []string{"2008-03-17"}
	opts := holidays.Options{Regions: []string{"ie"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "St. Patrick's Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "St. Patrick's Day", hols)
		}
	}
}

func TestIE_002_EasterMonday(t *testing.T) {
	dates := []string{"2008-03-24"}
	opts := holidays.Options{Regions: []string{"ie"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Easter Monday") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Easter Monday", hols)
		}
	}
}

func TestIE_003_MayDay(t *testing.T) {
	dates := []string{"2008-05-05"}
	opts := holidays.Options{Regions: []string{"ie"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "May Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "May Day", hols)
		}
	}
}

func TestIE_004_JuneBankHoliday(t *testing.T) {
	dates := []string{"2008-06-02"}
	opts := holidays.Options{Regions: []string{"ie"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "June Bank Holiday") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "June Bank Holiday", hols)
		}
	}
}

func TestIE_005_AugustBankHoliday(t *testing.T) {
	dates := []string{"2008-08-04"}
	opts := holidays.Options{Regions: []string{"ie"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "August Bank Holiday") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "August Bank Holiday", hols)
		}
	}
}

func TestIE_006_OctoberBankHoliday(t *testing.T) {
	dates := []string{"2008-10-27"}
	opts := holidays.Options{Regions: []string{"ie"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "October Bank Holiday") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "October Bank Holiday", hols)
		}
	}
}

func TestIE_007_ChristmasDay(t *testing.T) {
	dates := []string{"2008-12-25"}
	opts := holidays.Options{Regions: []string{"ie"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Christmas Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols)
		}
	}
}

func TestIE_008_StStephenSDay(t *testing.T) {
	dates := []string{"2008-12-26"}
	opts := holidays.Options{Regions: []string{"ie"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "St. Stephen's Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "St. Stephen's Day", hols)
		}
	}
}

func TestIE_009_NewYearSDay(t *testing.T) {
	dates := []string{"2012-01-02"}
	opts := holidays.Options{Regions: []string{"ie"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "New Year's Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols)
		}
	}
}

func TestIE_010_StPatrickSDay(t *testing.T) {
	dates := []string{"2012-03-19"}
	opts := holidays.Options{Regions: []string{"ie"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "St. Patrick's Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "St. Patrick's Day", hols)
		}
	}
}

func TestIE_011_EasterMonday(t *testing.T) {
	dates := []string{"2012-04-09"}
	opts := holidays.Options{Regions: []string{"ie"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Easter Monday") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Easter Monday", hols)
		}
	}
}

func TestIE_012_MayDay(t *testing.T) {
	dates := []string{"2012-05-07"}
	opts := holidays.Options{Regions: []string{"ie"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "May Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "May Day", hols)
		}
	}
}

func TestIE_013_JuneBankHoliday(t *testing.T) {
	dates := []string{"2012-06-04"}
	opts := holidays.Options{Regions: []string{"ie"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "June Bank Holiday") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "June Bank Holiday", hols)
		}
	}
}

func TestIE_014_AugustBankHoliday(t *testing.T) {
	dates := []string{"2012-08-06"}
	opts := holidays.Options{Regions: []string{"ie"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "August Bank Holiday") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "August Bank Holiday", hols)
		}
	}
}

func TestIE_015_OctoberBankHoliday(t *testing.T) {
	dates := []string{"2012-10-29"}
	opts := holidays.Options{Regions: []string{"ie"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "October Bank Holiday") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "October Bank Holiday", hols)
		}
	}
}

func TestIE_016_ChristmasDay(t *testing.T) {
	dates := []string{"2011-12-26"}
	opts := holidays.Options{Regions: []string{"ie"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Christmas Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols)
		}
	}
}

func TestIE_017_StStephenSDay(t *testing.T) {
	dates := []string{"2011-12-27"}
	opts := holidays.Options{Regions: []string{"ie"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "St. Stephen's Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "St. Stephen's Day", hols)
		}
	}
}

func TestIE_018_ChristmasDay(t *testing.T) {
	dates := []string{"2012-12-25"}
	opts := holidays.Options{Regions: []string{"ie"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Christmas Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols)
		}
	}
}

func TestIE_019_StStephenSDay(t *testing.T) {
	dates := []string{"2012-12-26"}
	opts := holidays.Options{Regions: []string{"ie"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "St. Stephen's Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "St. Stephen's Day", hols)
		}
	}
}

func TestIE_020_StStephenSDay(t *testing.T) {
	dates := []string{"2015-12-28"}
	opts := holidays.Options{Regions: []string{"ie"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "St. Stephen's Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "St. Stephen's Day", hols)
		}
	}
}
