// Code generated by gen-holidays from definitions/it.yaml@v8.0.0. DO NOT EDIT.

package definitions_test

import (
	"testing"

	holidays "github.com/ppeble/go-holidays/pkg"
)

func TestIT_000_Capodanno(t *testing.T) {
	dates := []string{"2007-01-01"}
	opts := holidays.Options{Regions: []string{"it"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Capodanno") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Capodanno", hols)
		}
	}
}

func TestIT_001_Epifania(t *testing.T) {
	dates := []string{"2007-01-06"}
	opts := holidays.Options{Regions: []string{"it"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Epifania") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Epifania", hols)
		}
	}
}

func TestIT_002_Pasqua(t *testing.T) {
	dates := []string{"2007-04-08"}
	opts := holidays.Options{Regions: []string{"it"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Pasqua") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Pasqua", hols)
		}
	}
}

func TestIT_003_LunedìDellAngelo(t *testing.T) {
	dates := []string{"2007-04-09"}
	opts := holidays.Options{Regions: []string{"it"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Lunedì dell'Angelo") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Lunedì dell'Angelo", hols)
		}
	}
}

func TestIT_004_FestaDellaLiberazione(t *testing.T) {
	dates := []string{"2007-04-25"}
	opts := holidays.Options{Regions: []string{"it"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Festa della Liberazione") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Festa della Liberazione", hols)
		}
	}
}

func TestIT_005_FestaDiSanLiberale(t *testing.T) {
	dates := []string{"2019-04-27"}
	opts := holidays.Options{Regions: []string{"it_tv"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Festa di San Liberale") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Festa di San Liberale", hols)
		}
	}
}

func TestIT_006_FestaDeiLavoratori(t *testing.T) {
	dates := []string{"2007-05-01"}
	opts := holidays.Options{Regions: []string{"it"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Festa dei Lavoratori") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Festa dei Lavoratori", hols)
		}
	}
}

func TestIT_007_FestaDiSanZeno(t *testing.T) {
	dates := []string{"2019-05-21"}
	opts := holidays.Options{Regions: []string{"it_vr"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Festa di San Zeno") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Festa di San Zeno", hols)
		}
	}
}

func TestIT_008_FestaDellaRepubblica(t *testing.T) {
	dates := []string{"2007-06-02"}
	opts := holidays.Options{Regions: []string{"it"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Festa della Repubblica") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Festa della Repubblica", hols)
		}
	}
}

func TestIT_009_FestaDiSantAntonioDiPadova(t *testing.T) {
	dates := []string{"2019-06-13"}
	opts := holidays.Options{Regions: []string{"it_pd"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Festa di Sant'Antonio di Padova") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Festa di Sant'Antonio di Padova", hols)
		}
	}
}

func TestIT_010_FestaDiSanGiovanniBattista(t *testing.T) {
	dates := []string{"2019-06-24"}
	opts := holidays.Options{Regions: []string{"it_fi", "it_ge", "it_to"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Festa di San Giovanni Battista") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Festa di San Giovanni Battista", hols)
		}
	}
}

func TestIT_011_Negative(t *testing.T) {
	dates := []string{"2019-06-24"}
	opts := holidays.Options{Regions: []string{"it"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if len(hols) > 0 {
			t.Errorf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols)
		}
	}
}

func TestIT_012_FestaDiSanPietroEPaolo(t *testing.T) {
	dates := []string{"2019-06-29"}
	opts := holidays.Options{Regions: []string{"it_rm"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Festa di San Pietro e Paolo") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Festa di San Pietro e Paolo", hols)
		}
	}
}

func TestIT_013_Negative(t *testing.T) {
	dates := []string{"2019-06-29"}
	opts := holidays.Options{Regions: []string{"it"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if len(hols) > 0 {
			t.Errorf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols)
		}
	}
}

func TestIT_014_Assunzione(t *testing.T) {
	dates := []string{"2007-08-15"}
	opts := holidays.Options{Regions: []string{"it"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Assunzione") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Assunzione", hols)
		}
	}
}

func TestIT_015_FestaDellaMadonnaDiMonteBerico(t *testing.T) {
	dates := []string{"2019-09-08"}
	opts := holidays.Options{Regions: []string{"it_vi"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Festa della Madonna di Monte Berico") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Festa della Madonna di Monte Berico", hols)
		}
	}
}

func TestIT_016_FestaDiSanFrancescoDAssisi(t *testing.T) {
	dates := []string{"2026-10-04"}
	opts := holidays.Options{Regions: []string{"it"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Festa di San Francesco d'Assisi") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Festa di San Francesco d'Assisi", hols)
		}
	}
}

func TestIT_017_Ognissanti(t *testing.T) {
	dates := []string{"2007-11-01"}
	opts := holidays.Options{Regions: []string{"it"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Ognissanti") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Ognissanti", hols)
		}
	}
}

func TestIT_018_FestaDiSanMartino(t *testing.T) {
	dates := []string{"2019-11-11"}
	opts := holidays.Options{Regions: []string{"it_bl"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Festa di San Martino") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Festa di San Martino", hols)
		}
	}
}

func TestIT_019_FestaDiSanBellino(t *testing.T) {
	dates := []string{"2019-11-26"}
	opts := holidays.Options{Regions: []string{"it_ro"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Festa di San Bellino") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Festa di San Bellino", hols)
		}
	}
}

func TestIT_020_ImmacolataConcezione(t *testing.T) {
	dates := []string{"2007-12-08"}
	opts := holidays.Options{Regions: []string{"it"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Immacolata Concezione") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Immacolata Concezione", hols)
		}
	}
}

func TestIT_021_Natale(t *testing.T) {
	dates := []string{"2007-12-25"}
	opts := holidays.Options{Regions: []string{"it"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Natale") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Natale", hols)
		}
	}
}

func TestIT_022_SantoStefano(t *testing.T) {
	dates := []string{"2007-12-26"}
	opts := holidays.Options{Regions: []string{"it"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Santo Stefano") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Santo Stefano", hols)
		}
	}
}
