// Code generated by gen-holidays from definitions/jp.yaml@v8.0.0. DO NOT EDIT.

package definitions_test

import (
	"testing"

	holidays "github.com/ppeble/go-holidays/pkg"
)

func TestJP_000_元日(t *testing.T) {
	dates := []string{"2008-01-01"}
	opts := holidays.Options{Regions: []string{"jp"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "元日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "元日", hols)
		}
	}
}

func TestJP_001_成人の日(t *testing.T) {
	dates := []string{"2010-01-11"}
	opts := holidays.Options{Regions: []string{"jp"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "成人の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "成人の日", hols)
		}
	}
}

func TestJP_002_建国記念の日(t *testing.T) {
	dates := []string{"2008-02-11"}
	opts := holidays.Options{Regions: []string{"jp"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "建国記念の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "建国記念の日", hols)
		}
	}
}

func TestJP_003_昭和の日(t *testing.T) {
	dates := []string{"2008-04-29"}
	opts := holidays.Options{Regions: []string{"jp"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "昭和の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "昭和の日", hols)
		}
	}
}

func TestJP_004_憲法記念日(t *testing.T) {
	dates := []string{"2008-05-03"}
	opts := holidays.Options{Regions: []string{"jp"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "憲法記念日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "憲法記念日", hols)
		}
	}
}

func TestJP_005_こどもの日(t *testing.T) {
	dates := []string{"2008-05-05"}
	opts := holidays.Options{Regions: []string{"jp"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "こどもの日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "こどもの日", hols)
		}
	}
}

func TestJP_006_海の日(t *testing.T) {
	dates := []string{"2010-07-19"}
	opts := holidays.Options{Regions: []string{"jp"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "海の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "海の日", hols)
		}
	}
}

func TestJP_007_敬老の日(t *testing.T) {
	dates := []string{"2010-09-20"}
	opts := holidays.Options{Regions: []string{"jp"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "敬老の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "敬老の日", hols)
		}
	}
}

func TestJP_008_体育の日(t *testing.T) {
	dates := []string{"2010-10-11"}
	opts := holidays.Options{Regions: []string{"jp"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "体育の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "体育の日", hols)
		}
	}
}

func TestJP_009_文化の日(t *testing.T) {
	dates := []string{"2008-11-03"}
	opts := holidays.Options{Regions: []string{"jp"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "文化の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "文化の日", hols)
		}
	}
}

func TestJP_010_勤労感謝の日(t *testing.T) {
	dates := []string{"2008-11-23"}
	opts := holidays.Options{Regions: []string{"jp"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "勤労感謝の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "勤労感謝の日", hols)
		}
	}
}

func TestJP_011_天皇誕生日(t *testing.T) {
	dates := []string{"2008-12-23"}
	opts := holidays.Options{Regions: []string{"jp"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "天皇誕生日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "天皇誕生日", hols)
		}
	}
}

func TestJP_012_振替休日(t *testing.T) {
	dates := []string{"2010-03-22"}
	opts := holidays.Options{Regions: []string{"jp"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "振替休日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "振替休日", hols)
		}
	}
}

func TestJP_013_振替休日(t *testing.T) {
	dates := []string{"2008-11-24"}
	opts := holidays.Options{Regions: []string{"jp"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "振替休日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "振替休日", hols)
		}
	}
}

func TestJP_014_振替休日(t *testing.T) {
	dates := []string{"2012-01-02"}
	opts := holidays.Options{Regions: []string{"jp"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "振替休日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "振替休日", hols)
		}
	}
}

func TestJP_015_振替休日(t *testing.T) {
	dates := []string{"2013-05-06"}
	opts := holidays.Options{Regions: []string{"jp"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "振替休日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "振替休日", hols)
		}
	}
}

func TestJP_016_振替休日(t *testing.T) {
	dates := []string{"2014-05-06"}
	opts := holidays.Options{Regions: []string{"jp"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "振替休日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "振替休日", hols)
		}
	}
}

func TestJP_017_振替休日(t *testing.T) {
	dates := []string{"2015-05-06"}
	opts := holidays.Options{Regions: []string{"jp"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "振替休日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "振替休日", hols)
		}
	}
}

func TestJP_018_振替休日(t *testing.T) {
	dates := []string{"2019-08-12"}
	opts := holidays.Options{Regions: []string{"jp"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "振替休日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "振替休日", hols)
		}
	}
}

func TestJP_019_春分の日(t *testing.T) {
	dates := []string{"2004-03-20"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "春分の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "春分の日", hols)
		}
	}
}

func TestJP_020_春分の日(t *testing.T) {
	dates := []string{"2005-03-20"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "春分の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "春分の日", hols)
		}
	}
}

func TestJP_021_春分の日(t *testing.T) {
	dates := []string{"2006-03-21"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "春分の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "春分の日", hols)
		}
	}
}

func TestJP_022_春分の日(t *testing.T) {
	dates := []string{"2007-03-21"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "春分の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "春分の日", hols)
		}
	}
}

func TestJP_023_春分の日(t *testing.T) {
	dates := []string{"2008-03-20"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "春分の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "春分の日", hols)
		}
	}
}

func TestJP_024_春分の日(t *testing.T) {
	dates := []string{"2009-03-20"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "春分の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "春分の日", hols)
		}
	}
}

func TestJP_025_春分の日(t *testing.T) {
	dates := []string{"2010-03-21"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "春分の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "春分の日", hols)
		}
	}
}

func TestJP_026_秋分の日(t *testing.T) {
	dates := []string{"2004-09-23"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "秋分の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "秋分の日", hols)
		}
	}
}

func TestJP_027_秋分の日(t *testing.T) {
	dates := []string{"2005-09-23"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "秋分の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "秋分の日", hols)
		}
	}
}

func TestJP_028_秋分の日(t *testing.T) {
	dates := []string{"2006-09-23"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "秋分の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "秋分の日", hols)
		}
	}
}

func TestJP_029_秋分の日(t *testing.T) {
	dates := []string{"2007-09-23"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "秋分の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "秋分の日", hols)
		}
	}
}

func TestJP_030_秋分の日(t *testing.T) {
	dates := []string{"2008-09-23"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "秋分の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "秋分の日", hols)
		}
	}
}

func TestJP_031_秋分の日(t *testing.T) {
	dates := []string{"2009-09-23"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "秋分の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "秋分の日", hols)
		}
	}
}

func TestJP_032_秋分の日(t *testing.T) {
	dates := []string{"2010-09-23"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "秋分の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "秋分の日", hols)
		}
	}
}

func TestJP_033_秋分の日(t *testing.T) {
	dates := []string{"2011-09-23"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "秋分の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "秋分の日", hols)
		}
	}
}

func TestJP_034_秋分の日(t *testing.T) {
	dates := []string{"2012-09-22"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "秋分の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "秋分の日", hols)
		}
	}
}

func TestJP_035_秋分の日(t *testing.T) {
	dates := []string{"2013-09-23"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "秋分の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "秋分の日", hols)
		}
	}
}

func TestJP_036_国民の休日(t *testing.T) {
	dates := []string{"2032-09-21"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "国民の休日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "国民の休日", hols)
		}
	}
}

func TestJP_037_国民の休日(t *testing.T) {
	dates := []string{"2049-09-21"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "国民の休日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "国民の休日", hols)
		}
	}
}

func TestJP_038_国民の休日(t *testing.T) {
	dates := []string{"2009-09-22"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "国民の休日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "国民の休日", hols)
		}
	}
}

func TestJP_039_国民の休日(t *testing.T) {
	dates := []string{"2015-09-22"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "国民の休日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "国民の休日", hols)
		}
	}
}

func TestJP_040_国民の休日(t *testing.T) {
	dates := []string{"2026-09-22"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "国民の休日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "国民の休日", hols)
		}
	}
}

func TestJP_041_海の日(t *testing.T) {
	dates := []string{"1996-07-20"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "海の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "海の日", hols)
		}
	}
}

func TestJP_042_海の日(t *testing.T) {
	dates := []string{"2002-07-20"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "海の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "海の日", hols)
		}
	}
}

func TestJP_043_海の日(t *testing.T) {
	dates := []string{"2003-07-21"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "海の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "海の日", hols)
		}
	}
}

func TestJP_044_海の日(t *testing.T) {
	dates := []string{"2004-07-19"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "海の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "海の日", hols)
		}
	}
}

func TestJP_045_海の日(t *testing.T) {
	dates := []string{"2005-07-18"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "海の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "海の日", hols)
		}
	}
}

func TestJP_046_海の日(t *testing.T) {
	dates := []string{"2006-07-17"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "海の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "海の日", hols)
		}
	}
}

func TestJP_047_海の日(t *testing.T) {
	dates := []string{"2007-07-16"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "海の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "海の日", hols)
		}
	}
}

func TestJP_048_海の日(t *testing.T) {
	dates := []string{"2009-07-20"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "海の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "海の日", hols)
		}
	}
}

func TestJP_049_海の日(t *testing.T) {
	dates := []string{"2013-07-15"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "海の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "海の日", hols)
		}
	}
}

func TestJP_050_海の日(t *testing.T) {
	dates := []string{"2014-07-21"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "海の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "海の日", hols)
		}
	}
}

func TestJP_051_海の日(t *testing.T) {
	dates := []string{"2019-07-15"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "海の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "海の日", hols)
		}
	}
}

func TestJP_052_Negative(t *testing.T) {
	dates := []string{"2020-07-20"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if len(hols) > 0 {
			t.Errorf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols)
		}
	}
}

func TestJP_053_海の日(t *testing.T) {
	dates := []string{"2020-07-23"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "海の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "海の日", hols)
		}
	}
}

func TestJP_054_海の日(t *testing.T) {
	dates := []string{"2021-07-22"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "海の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "海の日", hols)
		}
	}
}

func TestJP_055_山の日(t *testing.T) {
	dates := []string{"2016-08-11"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "山の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "山の日", hols)
		}
	}
}

func TestJP_056_山の日(t *testing.T) {
	dates := []string{"2017-08-11"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "山の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "山の日", hols)
		}
	}
}

func TestJP_057_山の日(t *testing.T) {
	dates := []string{"2018-08-11"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "山の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "山の日", hols)
		}
	}
}

func TestJP_058_山の日(t *testing.T) {
	dates := []string{"2019-08-11"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "山の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "山の日", hols)
		}
	}
}

func TestJP_059_山の日(t *testing.T) {
	dates := []string{"2020-08-10"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "山の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "山の日", hols)
		}
	}
}

func TestJP_060_Negative(t *testing.T) {
	dates := []string{"2020-08-11"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if len(hols) > 0 {
			t.Errorf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols)
		}
	}
}

func TestJP_061_山の日(t *testing.T) {
	dates := []string{"2021-08-08"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "山の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "山の日", hols)
		}
	}
}

func TestJP_062_振替休日(t *testing.T) {
	dates := []string{"2021-08-09"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "振替休日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "振替休日", hols)
		}
	}
}

func TestJP_063_山の日(t *testing.T) {
	dates := []string{"2022-08-11"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "山の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "山の日", hols)
		}
	}
}

func TestJP_064_Negative(t *testing.T) {
	dates := []string{"2015-08-11"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if len(hols) > 0 {
			t.Errorf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols)
		}
	}
}

func TestJP_065_Negative(t *testing.T) {
	dates := []string{"1998-09-22"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if len(hols) > 0 {
			t.Errorf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols)
		}
	}
}

func TestJP_066_天皇誕生日(t *testing.T) {
	dates := []string{"2018-12-23"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "天皇誕生日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "天皇誕生日", hols)
		}
	}
}

func TestJP_067_Negative(t *testing.T) {
	dates := []string{"2019-02-23"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if len(hols) > 0 {
			t.Errorf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols)
		}
	}
}

func TestJP_068_Negative(t *testing.T) {
	dates := []string{"2019-12-23"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if len(hols) > 0 {
			t.Errorf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols)
		}
	}
}

func TestJP_069_天皇誕生日(t *testing.T) {
	dates := []string{"2020-02-23"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "天皇誕生日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "天皇誕生日", hols)
		}
	}
}

func TestJP_070_体育の日(t *testing.T) {
	dates := []string{"2019-10-14"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "体育の日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "体育の日", hols)
		}
	}
}

func TestJP_071_スポーツの日(t *testing.T) {
	dates := []string{"2020-07-24"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "スポーツの日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "スポーツの日", hols)
		}
	}
}

func TestJP_072_Negative(t *testing.T) {
	dates := []string{"2020-10-12"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if len(hols) > 0 {
			t.Errorf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols)
		}
	}
}

func TestJP_073_スポーツの日(t *testing.T) {
	dates := []string{"2021-07-23"}
	opts := holidays.Options{Regions: []string{"jp"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "スポーツの日") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "スポーツの日", hols)
		}
	}
}
