// Code generated by gen-holidays from definitions/ke.yaml@v8.0.0. DO NOT EDIT.

package definitions_test

import (
	"testing"

	holidays "github.com/ppeble/go-holidays/pkg"
)

func TestKE_000_GoodFriday(t *testing.T) {
	dates := []string{"2008-03-21"}
	opts := holidays.Options{Regions: []string{"ke"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Good Friday") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Good Friday", hols)
		}
	}
}

func TestKE_001_EasterMonday(t *testing.T) {
	dates := []string{"2008-03-24"}
	opts := holidays.Options{Regions: []string{"ke"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Easter Monday") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Easter Monday", hols)
		}
	}
}

func TestKE_002_NewYearSDay(t *testing.T) {
	dates := []string{"2008-01-01"}
	opts := holidays.Options{Regions: []string{"ke"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "New Year's Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols)
		}
	}
}

func TestKE_003_LabourDay(t *testing.T) {
	dates := []string{"2008-05-01"}
	opts := holidays.Options{Regions: []string{"ke"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Labour Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Labour Day", hols)
		}
	}
}

func TestKE_004_MadarakaDay(t *testing.T) {
	dates := []string{"2019-06-01"}
	opts := holidays.Options{Regions: []string{"ke"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Madaraka Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Madaraka Day", hols)
		}
	}
}

func TestKE_005_HudumaDay(t *testing.T) {
	dates := []string{"2018-10-10"}
	opts := holidays.Options{Regions: []string{"ke"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Huduma Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Huduma Day", hols)
		}
	}
}

func TestKE_006_MashujaaDay(t *testing.T) {
	dates := []string{"2018-10-20"}
	opts := holidays.Options{Regions: []string{"ke"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Mashujaa Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Mashujaa Day", hols)
		}
	}
}

func TestKE_007_JamhuriDay(t *testing.T) {
	dates := []string{"2019-12-12"}
	opts := holidays.Options{Regions: []string{"ke"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Jamhuri Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Jamhuri Day", hols)
		}
	}
}

func TestKE_008_ChristmasDay(t *testing.T) {
	dates := []string{"2008-12-25"}
	opts := holidays.Options{Regions: []string{"ke"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Christmas Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols)
		}
	}
}

func TestKE_009_UtamaduniDay(t *testing.T) {
	dates := []string{"2018-12-26"}
	opts := holidays.Options{Regions: []string{"ke"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Utamaduni Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Utamaduni Day", hols)
		}
	}
}
