// Code generated by gen-holidays from definitions/kr.yaml@v7.0.0. DO NOT EDIT.

package definitions_test

import (
	"testing"

	holidays "github.com/ppeble/go-holidays/pkg"
)

func TestKR_000_설날(t *testing.T) {
	dates := []string{"2016-02-08"}
	opts := holidays.Options{Regions: []string{"kr"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "설날") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "설날", hols)
		}
	}
}

func TestKR_001_설날연휴(t *testing.T) {
	dates := []string{"2017-01-29"}
	opts := holidays.Options{Regions: []string{"kr"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "설날 연휴") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "설날 연휴", hols)
		}
	}
}

func TestKR_002_석가탄신일(t *testing.T) {
	dates := []string{"2016-05-14"}
	opts := holidays.Options{Regions: []string{"kr"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "석가탄신일") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "석가탄신일", hols)
		}
	}
}

func TestKR_003_추석(t *testing.T) {
	dates := []string{"2016-09-15"}
	opts := holidays.Options{Regions: []string{"kr"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "추석") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "추석", hols)
		}
	}
}

func TestKR_004_31절(t *testing.T) {
	dates := []string{"2016-03-01"}
	opts := holidays.Options{Regions: []string{"kr"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "3·1절") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "3·1절", hols)
		}
	}
}

func TestKR_005_어린이날(t *testing.T) {
	dates := []string{"2016-05-05"}
	opts := holidays.Options{Regions: []string{"kr"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "어린이날") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "어린이날", hols)
		}
	}
}

func TestKR_006_현충일(t *testing.T) {
	dates := []string{"2016-06-06"}
	opts := holidays.Options{Regions: []string{"kr"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "현충일") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "현충일", hols)
		}
	}
}

func TestKR_007_제헌절(t *testing.T) {
	dates := []string{"2016-07-17"}
	opts := holidays.Options{Regions: []string{"kr"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "제헌절") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "제헌절", hols)
		}
	}
}

func TestKR_008_광복절(t *testing.T) {
	dates := []string{"2016-08-15"}
	opts := holidays.Options{Regions: []string{"kr"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "광복절") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "광복절", hols)
		}
	}
}

func TestKR_009_개천절(t *testing.T) {
	dates := []string{"2016-10-03"}
	opts := holidays.Options{Regions: []string{"kr"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "개천절") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "개천절", hols)
		}
	}
}

func TestKR_010_한글날(t *testing.T) {
	dates := []string{"2016-10-09"}
	opts := holidays.Options{Regions: []string{"kr"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "한글날") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "한글날", hols)
		}
	}
}

func TestKR_011_크리스마스(t *testing.T) {
	dates := []string{"2016-12-25"}
	opts := holidays.Options{Regions: []string{"kr"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "크리스마스") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "크리스마스", hols)
		}
	}
}

func TestKR_012_설날(t *testing.T) {
	dates := []string{"2017-01-28"}
	opts := holidays.Options{Regions: []string{"kr"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "설날") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "설날", hols)
		}
	}
}
