// Code generated by gen-holidays from definitions/kz.yaml@v8.0.0. DO NOT EDIT.

package definitions_test

import (
	"testing"

	holidays "github.com/ppeble/go-holidays/pkg"
)

func TestKZ_000_JańaJyl(t *testing.T) {
	dates := []string{"2020-1-1"}
	opts := holidays.Options{Regions: []string{"kz"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Jańa jyl") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Jańa jyl", hols)
		}
	}
}

func TestKZ_001_JańaJyl(t *testing.T) {
	dates := []string{"2020-1-2"}
	opts := holidays.Options{Regions: []string{"kz"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Jańa jyl") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Jańa jyl", hols)
		}
	}
}

func TestKZ_002_HalyqaralyqÁıelderKúni(t *testing.T) {
	dates := []string{"2020-3-8"}
	opts := holidays.Options{Regions: []string{"kz"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Halyqaralyq áıelder kúni") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Halyqaralyq áıelder kúni", hols)
		}
	}
}

func TestKZ_003_NaýryzMeıramy(t *testing.T) {
	dates := []string{"2020-3-21"}
	opts := holidays.Options{Regions: []string{"kz"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Naýryz Meıramy") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Naýryz Meıramy", hols)
		}
	}
}

func TestKZ_004_NaýryzMeıramy(t *testing.T) {
	dates := []string{"2020-3-22"}
	opts := holidays.Options{Regions: []string{"kz"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Naýryz Meıramy") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Naýryz Meıramy", hols)
		}
	}
}

func TestKZ_005_NaýryzMeıramy(t *testing.T) {
	dates := []string{"2020-3-23"}
	opts := holidays.Options{Regions: []string{"kz"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Naýryz Meıramy") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Naýryz Meıramy", hols)
		}
	}
}

func TestKZ_006_QazaqstanHalqynyńBirligiMerekesi(t *testing.T) {
	dates := []string{"2020-5-1"}
	opts := holidays.Options{Regions: []string{"kz"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Qazaqstan halqynyń birligi merekesi") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Qazaqstan halqynyń birligi merekesi", hols)
		}
	}
}

func TestKZ_007_OtanQorǵaýshyKuni(t *testing.T) {
	dates := []string{"2020-5-7"}
	opts := holidays.Options{Regions: []string{"kz"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Otan Qorǵaýshy kuni") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Otan Qorǵaýshy kuni", hols)
		}
	}
}

func TestKZ_008_JeńisKúni(t *testing.T) {
	dates := []string{"2020-5-9"}
	opts := holidays.Options{Regions: []string{"kz"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Jeńis kúni") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Jeńis kúni", hols)
		}
	}
}

func TestKZ_009_AstanaKúni(t *testing.T) {
	dates := []string{"2020-7-6"}
	opts := holidays.Options{Regions: []string{"kz"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Astana kúni") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Astana kúni", hols)
		}
	}
}

func TestKZ_010_QazaqstanRespýblıkasynyńKonstıtýcıyasyKúni(t *testing.T) {
	dates := []string{"2020-8-30"}
	opts := holidays.Options{Regions: []string{"kz"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Qazaqstan Respýblıkasynyń Konstıtýcıyasy kúni") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Qazaqstan Respýblıkasynyń Konstıtýcıyasy kúni", hols)
		}
	}
}

func TestKZ_011_TúńǵyshPrezıdentKúni(t *testing.T) {
	dates := []string{"2020-12-1"}
	opts := holidays.Options{Regions: []string{"kz"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Túńǵysh Prezıdent kúni") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Túńǵysh Prezıdent kúni", hols)
		}
	}
}

func TestKZ_012_TáýelsizdikKúni(t *testing.T) {
	dates := []string{"2020-12-16"}
	opts := holidays.Options{Regions: []string{"kz"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Táýelsizdik kúni") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Táýelsizdik kúni", hols)
		}
	}
}

func TestKZ_013_TáýelsizdikKúni(t *testing.T) {
	dates := []string{"2020-12-17"}
	opts := holidays.Options{Regions: []string{"kz"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Táýelsizdik kúni") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Táýelsizdik kúni", hols)
		}
	}
}
