// Code generated by gen-holidays from definitions/ma.yaml@v6.1.1. DO NOT EDIT.

package definitions_test

import (
	"testing"

	holidays "github.com/ppeble/go-holidays/pkg"
)

func TestMA_000_RasLÂm(t *testing.T) {
	dates := []string{"2007-01-01"}
	opts := holidays.Options{Regions: []string{"ma"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Ras l' âm") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Ras l' âm", hols)
		}
	}
}

func TestMA_001_TakdimWatikatAlIstiqlal(t *testing.T) {
	dates := []string{"2007-01-11"}
	opts := holidays.Options{Regions: []string{"ma"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Takdim watikat al-istiqlal") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Takdim watikat al-istiqlal", hols)
		}
	}
}

func TestMA_002_EidAshShughl(t *testing.T) {
	dates := []string{"2007-05-01"}
	opts := holidays.Options{Regions: []string{"ma"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Eid Ash-Shughl") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Eid Ash-Shughl", hols)
		}
	}
}

func TestMA_003_EidAlÂrch(t *testing.T) {
	dates := []string{"2007-07-30"}
	opts := holidays.Options{Regions: []string{"ma"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Eid Al-Ârch") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Eid Al-Ârch", hols)
		}
	}
}

func TestMA_004_ZikraOuedEdDahab(t *testing.T) {
	dates := []string{"2007-08-14"}
	opts := holidays.Options{Regions: []string{"ma"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Zikra Oued Ed-Dahab") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Zikra Oued Ed-Dahab", hols)
		}
	}
}

func TestMA_005_ThawratAlMalikWaShâab(t *testing.T) {
	dates := []string{"2007-08-20"}
	opts := holidays.Options{Regions: []string{"ma"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Thawrat al malik wa shâab") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Thawrat al malik wa shâab", hols)
		}
	}
}

func TestMA_006_EidAlMilad(t *testing.T) {
	dates := []string{"2007-08-21"}
	opts := holidays.Options{Regions: []string{"ma"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Eid Al Milad") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Eid Al Milad", hols)
		}
	}
}

func TestMA_007_EidAlMassiraAlKhadra(t *testing.T) {
	dates := []string{"2007-11-06"}
	opts := holidays.Options{Regions: []string{"ma"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Eid Al Massira Al Khadra") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Eid Al Massira Al Khadra", hols)
		}
	}
}

func TestMA_008_EidAlIstiqulal(t *testing.T) {
	dates := []string{"2007-11-18"}
	opts := holidays.Options{Regions: []string{"ma"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Eid Al Istiqulal") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Eid Al Istiqulal", hols)
		}
	}
}
