// Code generated by gen-holidays from definitions/mc.yaml@v6.1.1. DO NOT EDIT.

package definitions_test

import (
	"testing"

	holidays "github.com/ppeble/go-holidays/pkg"
)

func TestMC_000_JourDeLAn(t *testing.T) {
	dates := []string{"2026-01-01"}
	opts := holidays.Options{Regions: []string{"mc"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Jour de l'an") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Jour de l'an", hols)
		}
	}
}

func TestMC_001_SainteDévote(t *testing.T) {
	dates := []string{"2026-01-27"}
	opts := holidays.Options{Regions: []string{"mc"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Sainte Dévote") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Sainte Dévote", hols)
		}
	}
}

func TestMC_002_LundiDePâques(t *testing.T) {
	dates := []string{"2026-04-06"}
	opts := holidays.Options{Regions: []string{"mc"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Lundi de Pâques") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Lundi de Pâques", hols)
		}
	}
}

func TestMC_003_FêteDuTravail(t *testing.T) {
	dates := []string{"2026-05-01"}
	opts := holidays.Options{Regions: []string{"mc"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Fête du Travail") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Fête du Travail", hols)
		}
	}
}

func TestMC_004_Ascension(t *testing.T) {
	dates := []string{"2026-05-14"}
	opts := holidays.Options{Regions: []string{"mc"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Ascension") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Ascension", hols)
		}
	}
}

func TestMC_005_LundiDePentecôte(t *testing.T) {
	dates := []string{"2026-05-25"}
	opts := holidays.Options{Regions: []string{"mc"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Lundi de Pentecôte") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Lundi de Pentecôte", hols)
		}
	}
}

func TestMC_006_FêteDieu(t *testing.T) {
	dates := []string{"2026-06-04"}
	opts := holidays.Options{Regions: []string{"mc"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Fête Dieu") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Fête Dieu", hols)
		}
	}
}

func TestMC_007_Assomption(t *testing.T) {
	dates := []string{"2026-08-15"}
	opts := holidays.Options{Regions: []string{"mc"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Assomption") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Assomption", hols)
		}
	}
}

func TestMC_008_Toussaint(t *testing.T) {
	dates := []string{"2026-11-01"}
	opts := holidays.Options{Regions: []string{"mc"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Toussaint") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Toussaint", hols)
		}
	}
}

func TestMC_009_FêteDuPrince(t *testing.T) {
	dates := []string{"2026-11-19"}
	opts := holidays.Options{Regions: []string{"mc"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Fête du Prince") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Fête du Prince", hols)
		}
	}
}

func TestMC_010_ImmaculéeConception(t *testing.T) {
	dates := []string{"2026-12-08"}
	opts := holidays.Options{Regions: []string{"mc"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Immaculée Conception") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Immaculée Conception", hols)
		}
	}
}

func TestMC_011_Noël(t *testing.T) {
	dates := []string{"2026-12-25"}
	opts := holidays.Options{Regions: []string{"mc"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Noël") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Noël", hols)
		}
	}
}

func TestMC_012_ImmaculéeConception(t *testing.T) {
	dates := []string{"2024-12-08"}
	opts := holidays.Options{Regions: []string{"mc"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Immaculée Conception") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Immaculée Conception", hols)
		}
	}
}

func TestMC_013_ImmaculéeConception(t *testing.T) {
	dates := []string{"2024-12-09"}
	opts := holidays.Options{Regions: []string{"mc"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Immaculée Conception") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Immaculée Conception", hols)
		}
	}
}

func TestMC_014_Toussaint(t *testing.T) {
	dates := []string{"2026-11-01"}
	opts := holidays.Options{Regions: []string{"mc"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Toussaint") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Toussaint", hols)
		}
	}
}

func TestMC_015_Toussaint(t *testing.T) {
	dates := []string{"2026-11-02"}
	opts := holidays.Options{Regions: []string{"mc"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Toussaint") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Toussaint", hols)
		}
	}
}
