// Code generated by gen-holidays from definitions/mt_en.yaml@v8.1.0. DO NOT EDIT.

package definitions

import (
	"github.com/ppeble/go-holidays/pkg/definition"
	"github.com/ppeble/go-holidays/pkg/engine"
)

var mt_enRules = []definition.HolidayRule{
	{
		Name:             "Good Friday",
		Regions:          []string{"mt_en"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -2,
	},
	{
		Name:    "New Year's Day",
		Regions: []string{"mt_en"},
		Month:   1,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:    "Feast of Saint Paul's Shipwreck in Malta",
		Regions: []string{"mt_en"},
		Month:   2,
		Mday:    10,
		Wday:    -1,
	},
	{
		Name:    "Feast of Saint Joseph",
		Regions: []string{"mt_en"},
		Month:   3,
		Mday:    19,
		Wday:    -1,
	},
	{
		Name:    "Freedom Day",
		Regions: []string{"mt_en"},
		Month:   3,
		Mday:    31,
		Wday:    -1,
	},
	{
		Name:    "Worker's Day",
		Regions: []string{"mt_en"},
		Month:   5,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:    "Sette Giugno",
		Regions: []string{"mt_en"},
		Month:   6,
		Mday:    7,
		Wday:    -1,
	},
	{
		Name:    "Feast of Saint Peter & Saint Paul",
		Regions: []string{"mt_en"},
		Month:   6,
		Mday:    29,
		Wday:    -1,
	},
	{
		Name:    "Feast of the Assumption of Our Lady",
		Regions: []string{"mt_en"},
		Month:   8,
		Mday:    15,
		Wday:    -1,
	},
	{
		Name:    "Victory Day",
		Regions: []string{"mt_en"},
		Month:   9,
		Mday:    8,
		Wday:    -1,
	},
	{
		Name:    "Independence Day",
		Regions: []string{"mt_en"},
		Month:   9,
		Mday:    21,
		Wday:    -1,
	},
	{
		Name:    "Feast of the Immaculate Conception",
		Regions: []string{"mt_en"},
		Month:   12,
		Mday:    8,
		Wday:    -1,
	},
	{
		Name:    "Republic Day",
		Regions: []string{"mt_en"},
		Month:   12,
		Mday:    13,
		Wday:    -1,
	},
	{
		Name:    "Christmas Day",
		Regions: []string{"mt_en"},
		Month:   12,
		Mday:    25,
		Wday:    -1,
	},
}

func init() {
	engine.RegisterCountry("mt_en", mt_enRules)
}
