// Code generated by gen-holidays from definitions/mt_en.yaml@v6.1.1. DO NOT EDIT.

package definitions_test

import (
	"testing"

	holidays "github.com/ppeble/go-holidays/pkg"
)

func TestMT_EN_000_NewYearSDay(t *testing.T) {
	dates := []string{"2017-1-1"}
	opts := holidays.Options{Regions: []string{"mt_en"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "New Year's Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols)
		}
	}
}

func TestMT_EN_001_FeastOfSaintPaulSShipwreckInMalta(t *testing.T) {
	dates := []string{"2017-2-10"}
	opts := holidays.Options{Regions: []string{"mt_en"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Feast of Saint Paul's Shipwreck in Malta") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Feast of Saint Paul's Shipwreck in Malta", hols)
		}
	}
}

func TestMT_EN_002_FeastOfSaintJoseph(t *testing.T) {
	dates := []string{"2017-3-19"}
	opts := holidays.Options{Regions: []string{"mt_en"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Feast of Saint Joseph") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Feast of Saint Joseph", hols)
		}
	}
}

func TestMT_EN_003_FreedomDay(t *testing.T) {
	dates := []string{"2017-3-31"}
	opts := holidays.Options{Regions: []string{"mt_en"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Freedom Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Freedom Day", hols)
		}
	}
}

func TestMT_EN_004_WorkerSDay(t *testing.T) {
	dates := []string{"2017-5-1"}
	opts := holidays.Options{Regions: []string{"mt_en"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Worker's Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Worker's Day", hols)
		}
	}
}

func TestMT_EN_005_SetteGiugno(t *testing.T) {
	dates := []string{"2017-6-7"}
	opts := holidays.Options{Regions: []string{"mt_en"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Sette Giugno") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Sette Giugno", hols)
		}
	}
}

func TestMT_EN_006_FeastOfSaintPeterSaintPaul(t *testing.T) {
	dates := []string{"2017-6-29"}
	opts := holidays.Options{Regions: []string{"mt_en"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Feast of Saint Peter & Saint Paul") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Feast of Saint Peter & Saint Paul", hols)
		}
	}
}

func TestMT_EN_007_FeastOfTheAssumptionOfOurLady(t *testing.T) {
	dates := []string{"2017-8-15"}
	opts := holidays.Options{Regions: []string{"mt_en"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Feast of the Assumption of Our Lady") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Feast of the Assumption of Our Lady", hols)
		}
	}
}

func TestMT_EN_008_VictoryDay(t *testing.T) {
	dates := []string{"2017-9-8"}
	opts := holidays.Options{Regions: []string{"mt_en"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Victory Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Victory Day", hols)
		}
	}
}

func TestMT_EN_009_IndependenceDay(t *testing.T) {
	dates := []string{"2017-9-21"}
	opts := holidays.Options{Regions: []string{"mt_en"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Independence Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Independence Day", hols)
		}
	}
}

func TestMT_EN_010_FeastOfTheImmaculateConception(t *testing.T) {
	dates := []string{"2017-12-8"}
	opts := holidays.Options{Regions: []string{"mt_en"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Feast of the Immaculate Conception") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Feast of the Immaculate Conception", hols)
		}
	}
}

func TestMT_EN_011_RepublicDay(t *testing.T) {
	dates := []string{"2017-12-13"}
	opts := holidays.Options{Regions: []string{"mt_en"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Republic Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Republic Day", hols)
		}
	}
}

func TestMT_EN_012_ChristmasDay(t *testing.T) {
	dates := []string{"2017-12-25"}
	opts := holidays.Options{Regions: []string{"mt_en"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Christmas Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols)
		}
	}
}

func TestMT_EN_013_GoodFriday(t *testing.T) {
	dates := []string{"2017-4-14", "2018-3-30", "2019-4-19"}
	opts := holidays.Options{Regions: []string{"mt_en"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Good Friday") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Good Friday", hols)
		}
	}
}
