// Code generated by gen-holidays from definitions/mt_mt.yaml@v7.0.0. DO NOT EDIT.

package definitions_test

import (
	"testing"

	holidays "github.com/ppeble/go-holidays/pkg"
)

func TestMT_MT_000_LEwwelTasSena(t *testing.T) {
	dates := []string{"2017-1-1"}
	opts := holidays.Options{Regions: []string{"mt_mt"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "L-Ewwel tas-Sena") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "L-Ewwel tas-Sena", hols)
		}
	}
}

func TestMT_MT_001_NawfraġjuTaSanPawl(t *testing.T) {
	dates := []string{"2017-2-10"}
	opts := holidays.Options{Regions: []string{"mt_mt"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Nawfraġju ta' San Pawl") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Nawfraġju ta' San Pawl", hols)
		}
	}
}

func TestMT_MT_002_SanĠużepp(t *testing.T) {
	dates := []string{"2017-3-19"}
	opts := holidays.Options{Regions: []string{"mt_mt"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "San Ġużepp") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "San Ġużepp", hols)
		}
	}
}

func TestMT_MT_003_JumIlĦelsien(t *testing.T) {
	dates := []string{"2017-3-31"}
	opts := holidays.Options{Regions: []string{"mt_mt"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Jum il-Ħelsien") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Jum il-Ħelsien", hols)
		}
	}
}

func TestMT_MT_004_JumIlĦaddiem(t *testing.T) {
	dates := []string{"2017-5-1"}
	opts := holidays.Options{Regions: []string{"mt_mt"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Jum il-Ħaddiem") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Jum il-Ħaddiem", hols)
		}
	}
}

func TestMT_MT_005_SetteGiugno(t *testing.T) {
	dates := []string{"2017-6-7"}
	opts := holidays.Options{Regions: []string{"mt_mt"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Sette Giugno") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Sette Giugno", hols)
		}
	}
}

func TestMT_MT_006_LImnarja(t *testing.T) {
	dates := []string{"2017-6-29"}
	opts := holidays.Options{Regions: []string{"mt_mt"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "L-Imnarja") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "L-Imnarja", hols)
		}
	}
}

func TestMT_MT_007_SantaMarija(t *testing.T) {
	dates := []string{"2017-8-15"}
	opts := holidays.Options{Regions: []string{"mt_mt"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Santa Marija") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Santa Marija", hols)
		}
	}
}

func TestMT_MT_008_JumIlVitorja(t *testing.T) {
	dates := []string{"2017-9-8"}
	opts := holidays.Options{Regions: []string{"mt_mt"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Jum il-Vitorja") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Jum il-Vitorja", hols)
		}
	}
}

func TestMT_MT_009_JumLIndipendenza(t *testing.T) {
	dates := []string{"2017-9-21"}
	opts := holidays.Options{Regions: []string{"mt_mt"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Jum l-Indipendenza") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Jum l-Indipendenza", hols)
		}
	}
}

func TestMT_MT_010_IlKunċizzjoni(t *testing.T) {
	dates := []string{"2017-12-8"}
	opts := holidays.Options{Regions: []string{"mt_mt"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Il-Kunċizzjoni") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Il-Kunċizzjoni", hols)
		}
	}
}

func TestMT_MT_011_JumIrRepubblika(t *testing.T) {
	dates := []string{"2017-12-13"}
	opts := holidays.Options{Regions: []string{"mt_mt"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Jum ir-Repubblika") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Jum ir-Repubblika", hols)
		}
	}
}

func TestMT_MT_012_IlMilied(t *testing.T) {
	dates := []string{"2017-12-25"}
	opts := holidays.Options{Regions: []string{"mt_mt"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Il-Milied") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Il-Milied", hols)
		}
	}
}

func TestMT_MT_013_IlĠimgħaLKbira(t *testing.T) {
	dates := []string{"2017-4-14", "2018-3-30", "2019-4-19"}
	opts := holidays.Options{Regions: []string{"mt_mt"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Il-Ġimgħa l-Kbira") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Il-Ġimgħa l-Kbira", hols)
		}
	}
}
