// Code generated by gen-holidays from definitions/my.yaml@v8.0.0. DO NOT EDIT.

package definitions

import (
	"github.com/ppeble/go-holidays/pkg/definition"
	"github.com/ppeble/go-holidays/pkg/engine"
)

var myRules = []definition.HolidayRule{
	{
		Name:     "New Year's Day",
		Regions:  []string{"my"},
		Month:    1,
		Mday:     1,
		Wday:     -1,
		Observed: "to_weekday_if_weekend",
	},
	{
		Name:    "Labour Day",
		Regions: []string{"my"},
		Month:   5,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:     "Agong's Birthday",
		Regions:  []string{"my"},
		Month:    6,
		Mday:     4,
		Wday:     -1,
		Observed: "to_weekday_if_weekend",
	},
	{
		Name:     "Independence Day",
		Regions:  []string{"my"},
		Month:    8,
		Mday:     31,
		Wday:     -1,
		Observed: "to_weekday_if_weekend",
	},
	{
		Name:     "Malaysia Day",
		Regions:  []string{"my"},
		Month:    9,
		Mday:     16,
		Wday:     -1,
		Observed: "to_weekday_if_weekend",
	},
	{
		Name:     "Christmas Day",
		Regions:  []string{"my"},
		Month:    12,
		Mday:     25,
		Wday:     -1,
		Observed: "to_weekday_if_weekend",
	},
}

func init() {
	engine.RegisterCountry("my", myRules)
}
