// Code generated by gen-holidays from definitions/my.yaml@v7.0.0. DO NOT EDIT.

package definitions_test

import (
	"testing"

	holidays "github.com/ppeble/go-holidays/pkg"
)

func TestMY_000_NewYearSDay(t *testing.T) {
	dates := []string{"2016-01-01"}
	opts := holidays.Options{Regions: []string{"my"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "New Year's Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols)
		}
	}
}

func TestMY_001_LabourDay(t *testing.T) {
	dates := []string{"2016-05-01"}
	opts := holidays.Options{Regions: []string{"my"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Labour Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Labour Day", hols)
		}
	}
}

func TestMY_002_AgongSBirthday(t *testing.T) {
	dates := []string{"2016-06-04"}
	opts := holidays.Options{Regions: []string{"my"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Agong's Birthday") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Agong's Birthday", hols)
		}
	}
}

func TestMY_003_IndependenceDay(t *testing.T) {
	dates := []string{"2016-08-31"}
	opts := holidays.Options{Regions: []string{"my"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Independence Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Independence Day", hols)
		}
	}
}

func TestMY_004_MalaysiaDay(t *testing.T) {
	dates := []string{"2016-09-16"}
	opts := holidays.Options{Regions: []string{"my"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Malaysia Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Malaysia Day", hols)
		}
	}
}

func TestMY_005_ChristmasDay(t *testing.T) {
	dates := []string{"2016-12-25"}
	opts := holidays.Options{Regions: []string{"my"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Christmas Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols)
		}
	}
}
