// Code generated by gen-holidays from definitions/no.yaml@v6.1.1. DO NOT EDIT.

package definitions_test

import (
	"testing"

	holidays "github.com/ppeble/go-holidays/pkg"
)

func TestNO_000_Nyttårsdag(t *testing.T) {
	dates := []string{"2010-01-01"}
	opts := holidays.Options{Regions: []string{"no"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Nyttårsdag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Nyttårsdag", hols)
		}
	}
}

func TestNO_001_1Mai(t *testing.T) {
	dates := []string{"2010-05-01"}
	opts := holidays.Options{Regions: []string{"no"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "1. mai") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "1. mai", hols)
		}
	}
}

func TestNO_002_17Mai(t *testing.T) {
	dates := []string{"2010-05-17"}
	opts := holidays.Options{Regions: []string{"no"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "17. mai") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "17. mai", hols)
		}
	}
}

func TestNO_003_Julaften(t *testing.T) {
	dates := []string{"2010-12-24"}
	opts := holidays.Options{Regions: []string{"no"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Julaften") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Julaften", hols)
		}
	}
}

func TestNO_004_1Juledag(t *testing.T) {
	dates := []string{"2010-12-25"}
	opts := holidays.Options{Regions: []string{"no"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "1. juledag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "1. juledag", hols)
		}
	}
}

func TestNO_005_2Juledag(t *testing.T) {
	dates := []string{"2010-12-26"}
	opts := holidays.Options{Regions: []string{"no"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "2. juledag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "2. juledag", hols)
		}
	}
}

func TestNO_006_Nyttårsaften(t *testing.T) {
	dates := []string{"2010-12-31"}
	opts := holidays.Options{Regions: []string{"no"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Nyttårsaften") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Nyttårsaften", hols)
		}
	}
}

func TestNO_007_Fastelavn(t *testing.T) {
	dates := []string{"2010-02-14"}
	opts := holidays.Options{Regions: []string{"no"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Fastelavn") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Fastelavn", hols)
		}
	}
}

func TestNO_008_Palmesøndag(t *testing.T) {
	dates := []string{"2010-03-28"}
	opts := holidays.Options{Regions: []string{"no"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Palmesøndag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Palmesøndag", hols)
		}
	}
}

func TestNO_009_Skjærtorsdag(t *testing.T) {
	dates := []string{"2010-04-01"}
	opts := holidays.Options{Regions: []string{"no"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Skjærtorsdag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Skjærtorsdag", hols)
		}
	}
}

func TestNO_010_Langfredag(t *testing.T) {
	dates := []string{"2010-04-02"}
	opts := holidays.Options{Regions: []string{"no"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Langfredag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Langfredag", hols)
		}
	}
}

func TestNO_011_1Påskedag(t *testing.T) {
	dates := []string{"2010-04-04"}
	opts := holidays.Options{Regions: []string{"no"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "1. påskedag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "1. påskedag", hols)
		}
	}
}

func TestNO_012_2Påskedag(t *testing.T) {
	dates := []string{"2010-04-05"}
	opts := holidays.Options{Regions: []string{"no"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "2. påskedag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "2. påskedag", hols)
		}
	}
}

func TestNO_013_KristiHimmelfartsdag(t *testing.T) {
	dates := []string{"2010-05-13"}
	opts := holidays.Options{Regions: []string{"no"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Kristi Himmelfartsdag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Kristi Himmelfartsdag", hols)
		}
	}
}

func TestNO_014_1Pinsedag(t *testing.T) {
	dates := []string{"2010-05-23"}
	opts := holidays.Options{Regions: []string{"no"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "1. pinsedag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "1. pinsedag", hols)
		}
	}
}

func TestNO_015_2Pinsedag(t *testing.T) {
	dates := []string{"2010-05-24"}
	opts := holidays.Options{Regions: []string{"no"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "2. pinsedag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "2. pinsedag", hols)
		}
	}
}
