// Code generated by gen-holidays from definitions/nyse.yaml@v8.0.0. DO NOT EDIT.

package definitions_test

import (
	"testing"

	holidays "github.com/ppeble/go-holidays/pkg"
)

func TestNYSE_000_NewYearSDay(t *testing.T) {
	dates := []string{"2008-01-01"}
	opts := holidays.Options{Regions: []string{"nyse"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "New Year's Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols)
		}
	}
}

func TestNYSE_001_NewYearSDay(t *testing.T) {
	dates := []string{"2017-01-02", "2012-01-02", "2011-01-01", "2006-01-02"}
	opts := holidays.Options{Regions: []string{"nyse"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "New Year's Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols)
		}
	}
}

func TestNYSE_002_MartinLutherKingJrDay(t *testing.T) {
	dates := []string{"2008-01-21"}
	opts := holidays.Options{Regions: []string{"nyse"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Martin Luther King, Jr. Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Martin Luther King, Jr. Day", hols)
		}
	}
}

func TestNYSE_003_PresidentsDay(t *testing.T) {
	dates := []string{"2008-02-18"}
	opts := holidays.Options{Regions: []string{"nyse"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Presidents' Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Presidents' Day", hols)
		}
	}
}

func TestNYSE_004_GoodFriday(t *testing.T) {
	dates := []string{"2008-03-21"}
	opts := holidays.Options{Regions: []string{"nyse"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Good Friday") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Good Friday", hols)
		}
	}
}

func TestNYSE_005_MemorialDay(t *testing.T) {
	dates := []string{"2008-05-26"}
	opts := holidays.Options{Regions: []string{"nyse"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Memorial Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Memorial Day", hols)
		}
	}
}

func TestNYSE_006_IndependenceDay(t *testing.T) {
	dates := []string{"2008-07-04"}
	opts := holidays.Options{Regions: []string{"nyse"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Independence Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Independence Day", hols)
		}
	}
}

func TestNYSE_007_LaborDay(t *testing.T) {
	dates := []string{"2008-09-01"}
	opts := holidays.Options{Regions: []string{"nyse"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Labor Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Labor Day", hols)
		}
	}
}

func TestNYSE_008_Thanksgiving(t *testing.T) {
	dates := []string{"2008-11-27"}
	opts := holidays.Options{Regions: []string{"nyse"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Thanksgiving") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Thanksgiving", hols)
		}
	}
}

func TestNYSE_009_ChristmasDay(t *testing.T) {
	dates := []string{"2008-12-25"}
	opts := holidays.Options{Regions: []string{"nyse"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Christmas Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols)
		}
	}
}

func TestNYSE_010_NewYearSDay(t *testing.T) {
	dates := []string{"2017-01-02", "2012-01-02", "2011-01-01", "2006-01-02"}
	opts := holidays.Options{Regions: []string{"nyse"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "New Year's Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols)
		}
	}
}

func TestNYSE_011_JuneteenthNationalIndependenceDay(t *testing.T) {
	dates := []string{"2022-06-20", "2023-06-19", "2024-06-19", "2027-06-18"}
	opts := holidays.Options{Regions: []string{"nyse"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Juneteenth National Independence Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Juneteenth National Independence Day", hols)
		}
	}
}

func TestNYSE_012_Negative(t *testing.T) {
	dates := []string{"2021-06-18"}
	opts := holidays.Options{Regions: []string{"nyse"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if len(hols) > 0 {
			t.Errorf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols)
		}
	}
}
