// Code generated by gen-holidays from definitions/pe.yaml@v6.1.1. DO NOT EDIT.

package definitions_test

import (
	"testing"

	holidays "github.com/ppeble/go-holidays/pkg"
)

func TestPE_000_AñoNuevo(t *testing.T) {
	dates := []string{"2016-01-01"}
	opts := holidays.Options{Regions: []string{"pe"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Año Nuevo") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Año Nuevo", hols)
		}
	}
}

func TestPE_001_DíaDeLosReyesMagos(t *testing.T) {
	dates := []string{"2016-01-06"}
	opts := holidays.Options{Regions: []string{"pe"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Día de los Reyes Magos") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de los Reyes Magos", hols)
		}
	}
}

func TestPE_002_JuevesSanto(t *testing.T) {
	dates := []string{"2016-03-24"}
	opts := holidays.Options{Regions: []string{"pe"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Jueves Santo") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Jueves Santo", hols)
		}
	}
}

func TestPE_003_ViernesSanto(t *testing.T) {
	dates := []string{"2016-03-25"}
	opts := holidays.Options{Regions: []string{"pe"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Viernes Santo") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Viernes Santo", hols)
		}
	}
}

func TestPE_004_Pascua(t *testing.T) {
	dates := []string{"2016-03-27"}
	opts := holidays.Options{Regions: []string{"pe"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Pascua") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Pascua", hols)
		}
	}
}

func TestPE_005_DíaDelTrabajador(t *testing.T) {
	dates := []string{"2016-05-01"}
	opts := holidays.Options{Regions: []string{"pe"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Día del Trabajador") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día del Trabajador", hols)
		}
	}
}

func TestPE_006_DíaDeLaMadre(t *testing.T) {
	dates := []string{"2016-05-08"}
	opts := holidays.Options{Regions: []string{"pe"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Día de la Madre") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de la Madre", hols)
		}
	}
}

func TestPE_007_DíaDeLaBandera(t *testing.T) {
	dates := []string{"2016-06-07"}
	opts := holidays.Options{Regions: []string{"pe"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Día de la Bandera") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de la Bandera", hols)
		}
	}
}

func TestPE_008_DíaDelPadre(t *testing.T) {
	dates := []string{"2016-06-19"}
	opts := holidays.Options{Regions: []string{"pe"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Día del Padre") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día del Padre", hols)
		}
	}
}

func TestPE_009_SanPabloYSanPedro(t *testing.T) {
	dates := []string{"2016-06-29"}
	opts := holidays.Options{Regions: []string{"pe"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "San Pablo y San Pedro") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "San Pablo y San Pedro", hols)
		}
	}
}

func TestPE_010_PrimerDíaDeLaIndependencia(t *testing.T) {
	dates := []string{"2016-07-28"}
	opts := holidays.Options{Regions: []string{"pe"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Primer Día de la Independencia") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Primer Día de la Independencia", hols)
		}
	}
}

func TestPE_011_SegundoDíaDeLaIndependencia(t *testing.T) {
	dates := []string{"2016-07-29"}
	opts := holidays.Options{Regions: []string{"pe"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Segundo Día de la Independencia") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Segundo Día de la Independencia", hols)
		}
	}
}

func TestPE_012_SantaRosaDeLima(t *testing.T) {
	dates := []string{"2016-08-30"}
	opts := holidays.Options{Regions: []string{"pe"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Santa Rosa de Lima") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Santa Rosa de Lima", hols)
		}
	}
}

func TestPE_013_DíaDeLasFuerzasArmadas(t *testing.T) {
	dates := []string{"2016-09-24"}
	opts := holidays.Options{Regions: []string{"pe"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Día de las Fuerzas Armadas") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de las Fuerzas Armadas", hols)
		}
	}
}

func TestPE_014_BatallaDeAngamos(t *testing.T) {
	dates := []string{"2016-10-08"}
	opts := holidays.Options{Regions: []string{"pe"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Batalla de Angamos") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Batalla de Angamos", hols)
		}
	}
}

func TestPE_015_TodosLosSantos(t *testing.T) {
	dates := []string{"2016-11-01"}
	opts := holidays.Options{Regions: []string{"pe"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Todos los Santos") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Todos los Santos", hols)
		}
	}
}

func TestPE_016_InmaculadaConcepción(t *testing.T) {
	dates := []string{"2016-12-08"}
	opts := holidays.Options{Regions: []string{"pe"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Inmaculada Concepción") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Inmaculada Concepción", hols)
		}
	}
}

func TestPE_017_NavidadDelSeñor(t *testing.T) {
	dates := []string{"2016-12-25"}
	opts := holidays.Options{Regions: []string{"pe"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Navidad del Señor") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Navidad del Señor", hols)
		}
	}
}
