// Code generated by gen-holidays from definitions/ph.yaml@v7.0.0. DO NOT EDIT.

package definitions_test

import (
	"testing"

	holidays "github.com/ppeble/go-holidays/pkg"
)

func TestPH_000_GoodFriday(t *testing.T) {
	dates := []string{"2015-04-03"}
	opts := holidays.Options{Regions: []string{"ph"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Good Friday") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Good Friday", hols)
		}
	}
}

func TestPH_001_TheDayOfValor(t *testing.T) {
	dates := []string{"2015-04-09"}
	opts := holidays.Options{Regions: []string{"ph"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "The Day of Valor") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "The Day of Valor", hols)
		}
	}
}

func TestPH_002_LaborDay(t *testing.T) {
	dates := []string{"2015-05-01"}
	opts := holidays.Options{Regions: []string{"ph"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Labor Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Labor Day", hols)
		}
	}
}

func TestPH_003_IndependenceDay(t *testing.T) {
	dates := []string{"2015-06-12"}
	opts := holidays.Options{Regions: []string{"ph"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Independence Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Independence Day", hols)
		}
	}
}

func TestPH_004_NinoyAquinoDay(t *testing.T) {
	dates := []string{"2015-08-21"}
	opts := holidays.Options{Regions: []string{"ph"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Ninoy Aquino Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Ninoy Aquino Day", hols)
		}
	}
}

func TestPH_005_NationalHeroesDay(t *testing.T) {
	dates := []string{"2015-08-31"}
	opts := holidays.Options{Regions: []string{"ph"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "National Heroes Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "National Heroes Day", hols)
		}
	}
}

func TestPH_006_BonifacioDay(t *testing.T) {
	dates := []string{"2015-11-30"}
	opts := holidays.Options{Regions: []string{"ph"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Bonifacio Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Bonifacio Day", hols)
		}
	}
}

func TestPH_007_ChristmasDay(t *testing.T) {
	dates := []string{"2015-12-25"}
	opts := holidays.Options{Regions: []string{"ph"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Christmas Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols)
		}
	}
}

func TestPH_008_RizalDay(t *testing.T) {
	dates := []string{"2015-12-30"}
	opts := holidays.Options{Regions: []string{"ph"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Rizal Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Rizal Day", hols)
		}
	}
}
