// Code generated by gen-holidays from definitions/pt.yaml@v8.0.0. DO NOT EDIT.

package definitions_test

import (
	"testing"

	holidays "github.com/ppeble/go-holidays/pkg"
)

func TestPT_000_AnoNovo(t *testing.T) {
	dates := []string{"2008-01-01"}
	opts := holidays.Options{Regions: []string{"pt"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Ano Novo") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Ano Novo", hols)
		}
	}
}

func TestPT_001_Carnaval(t *testing.T) {
	dates := []string{"2005-02-08"}
	opts := holidays.Options{Regions: []string{"pt"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Carnaval") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Carnaval", hols)
		}
	}
}

func TestPT_002_Carnaval(t *testing.T) {
	dates := []string{"2006-02-28"}
	opts := holidays.Options{Regions: []string{"pt"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Carnaval") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Carnaval", hols)
		}
	}
}

func TestPT_003_Carnaval(t *testing.T) {
	dates := []string{"2007-02-20"}
	opts := holidays.Options{Regions: []string{"pt"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Carnaval") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Carnaval", hols)
		}
	}
}

func TestPT_004_Carnaval(t *testing.T) {
	dates := []string{"2008-02-05"}
	opts := holidays.Options{Regions: []string{"pt"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Carnaval") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Carnaval", hols)
		}
	}
}

func TestPT_005_SextaFeiraSanta(t *testing.T) {
	dates := []string{"2008-03-21"}
	opts := holidays.Options{Regions: []string{"pt"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Sexta-feira Santa") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Sexta-feira Santa", hols)
		}
	}
}

func TestPT_006_Páscoa(t *testing.T) {
	dates := []string{"2008-03-23"}
	opts := holidays.Options{Regions: []string{"pt"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Páscoa") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Páscoa", hols)
		}
	}
}

func TestPT_007_Páscoa(t *testing.T) {
	dates := []string{"2016-03-27"}
	opts := holidays.Options{Regions: []string{"pt"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Páscoa") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Páscoa", hols)
		}
	}
}

func TestPT_008_DiaDaLiberdade(t *testing.T) {
	dates := []string{"2008-04-25"}
	opts := holidays.Options{Regions: []string{"pt"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Dia da Liberdade") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Dia da Liberdade", hols)
		}
	}
}

func TestPT_009_DiaDoTrabalhador(t *testing.T) {
	dates := []string{"2008-05-01"}
	opts := holidays.Options{Regions: []string{"pt"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Dia do Trabalhador") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Dia do Trabalhador", hols)
		}
	}
}

func TestPT_010_CorpoDeDeus(t *testing.T) {
	dates := []string{"2016-05-26"}
	opts := holidays.Options{Regions: []string{"pt"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Corpo de Deus") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Corpo de Deus", hols)
		}
	}
}

func TestPT_011_DiaDePortugal(t *testing.T) {
	dates := []string{"2008-06-10"}
	opts := holidays.Options{Regions: []string{"pt"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Dia de Portugal") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Dia de Portugal", hols)
		}
	}
}

func TestPT_012_AssunçãoDeNossaSenhora(t *testing.T) {
	dates := []string{"2008-08-15"}
	opts := holidays.Options{Regions: []string{"pt"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Assunção de Nossa Senhora") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Assunção de Nossa Senhora", hols)
		}
	}
}

func TestPT_013_DiaDaRepública(t *testing.T) {
	dates := []string{"2008-10-05"}
	opts := holidays.Options{Regions: []string{"pt"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Dia da República") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Dia da República", hols)
		}
	}
}

func TestPT_014_DiaDeTodosOsSantos(t *testing.T) {
	dates := []string{"2008-11-01"}
	opts := holidays.Options{Regions: []string{"pt"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Dia de Todos-os-Santos") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Dia de Todos-os-Santos", hols)
		}
	}
}

func TestPT_015_RestauraçãoDaIndependência(t *testing.T) {
	dates := []string{"2008-12-01"}
	opts := holidays.Options{Regions: []string{"pt"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Restauração da Independência") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Restauração da Independência", hols)
		}
	}
}

func TestPT_016_ImaculadaConceição(t *testing.T) {
	dates := []string{"2008-12-08"}
	opts := holidays.Options{Regions: []string{"pt"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Imaculada Conceição") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Imaculada Conceição", hols)
		}
	}
}

func TestPT_017_Natal(t *testing.T) {
	dates := []string{"2008-12-25"}
	opts := holidays.Options{Regions: []string{"pt"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Natal") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Natal", hols)
		}
	}
}
