// Code generated by gen-holidays from definitions/rs_cyrl.yaml@v7.0.0. DO NOT EDIT.

package definitions_test

import (
	"testing"

	holidays "github.com/ppeble/go-holidays/pkg"
)

func TestRS_CYRL_000_НоваГодина(t *testing.T) {
	dates := []string{"2017-1-1", "2017-1-2"}
	opts := holidays.Options{Regions: []string{"rs_cyrl"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Нова Година") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Нова Година", hols)
		}
	}
}

func TestRS_CYRL_001_Божић(t *testing.T) {
	dates := []string{"2017-1-7"}
	opts := holidays.Options{Regions: []string{"rs_cyrl"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Божић") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Божић", hols)
		}
	}
}

func TestRS_CYRL_002_СветиСаваСавиндан(t *testing.T) {
	dates := []string{"2017-1-27"}
	opts := holidays.Options{Regions: []string{"rs_cyrl"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Свети Сава (Савиндан)") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Свети Сава (Савиндан)", hols)
		}
	}
}

func TestRS_CYRL_003_ДанДржавностиСрбије(t *testing.T) {
	dates := []string{"2017-2-15", "2017-2-16"}
	opts := holidays.Options{Regions: []string{"rs_cyrl"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Дан државности Србије") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Дан државности Србије", hols)
		}
	}
}

func TestRS_CYRL_004_ПразникРада(t *testing.T) {
	dates := []string{"2017-5-1", "2017-5-2"}
	opts := holidays.Options{Regions: []string{"rs_cyrl"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Празник рада") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Празник рада", hols)
		}
	}
}

func TestRS_CYRL_005_ДанПобедеНадФашизмом(t *testing.T) {
	dates := []string{"2017-5-9"}
	opts := holidays.Options{Regions: []string{"rs_cyrl"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Дан победе над фашизмом") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Дан победе над фашизмом", hols)
		}
	}
}

func TestRS_CYRL_006_Видовдан(t *testing.T) {
	dates := []string{"2017-6-28"}
	opts := holidays.Options{Regions: []string{"rs_cyrl"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Видовдан") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Видовдан", hols)
		}
	}
}

func TestRS_CYRL_007_ДанПримирја(t *testing.T) {
	dates := []string{"2017-11-11"}
	opts := holidays.Options{Regions: []string{"rs_cyrl"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Дан примирја") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Дан примирја", hols)
		}
	}
}

func TestRS_CYRL_008_ВеликиПетак(t *testing.T) {
	dates := []string{"2017-4-14", "2018-4-6", "2019-4-26"}
	opts := holidays.Options{Regions: []string{"rs_cyrl"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Велики петак") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Велики петак", hols)
		}
	}
}

func TestRS_CYRL_009_ВеликаСубота(t *testing.T) {
	dates := []string{"2017-4-15", "2018-4-7", "2019-4-27"}
	opts := holidays.Options{Regions: []string{"rs_cyrl"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Велика Субота") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Велика Субота", hols)
		}
	}
}

func TestRS_CYRL_010_Васкрс(t *testing.T) {
	dates := []string{"2017-4-16", "2018-4-8", "2019-4-28"}
	opts := holidays.Options{Regions: []string{"rs_cyrl"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Васкрс") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Васкрс", hols)
		}
	}
}

func TestRS_CYRL_011_ВаскрсниПонедељак(t *testing.T) {
	dates := []string{"2017-4-17", "2018-4-9", "2019-4-29"}
	opts := holidays.Options{Regions: []string{"rs_cyrl"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Васкрсни понедељак") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Васкрсни понедељак", hols)
		}
	}
}
