// Code generated by gen-holidays from definitions/rs_la.yaml@v8.0.0. DO NOT EDIT.

package definitions_test

import (
	"testing"

	holidays "github.com/ppeble/go-holidays/pkg"
)

func TestRS_LA_000_NovaGodina(t *testing.T) {
	dates := []string{"2017-1-1", "2017-1-2"}
	opts := holidays.Options{Regions: []string{"rs_la"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Nova Godina") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Nova Godina", hols)
		}
	}
}

func TestRS_LA_001_Božić(t *testing.T) {
	dates := []string{"2017-1-7"}
	opts := holidays.Options{Regions: []string{"rs_la"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Božić") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Božić", hols)
		}
	}
}

func TestRS_LA_002_DanSvetogSave(t *testing.T) {
	dates := []string{"2017-1-27"}
	opts := holidays.Options{Regions: []string{"rs_la"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Dan Svetog Save") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Dan Svetog Save", hols)
		}
	}
}

func TestRS_LA_003_DanDržavnostiSrbije(t *testing.T) {
	dates := []string{"2017-2-15", "2017-2-16"}
	opts := holidays.Options{Regions: []string{"rs_la"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Dan državnosti Srbije") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Dan državnosti Srbije", hols)
		}
	}
}

func TestRS_LA_004_PraznikRada(t *testing.T) {
	dates := []string{"2017-5-1", "2017-5-2"}
	opts := holidays.Options{Regions: []string{"rs_la"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Praznik rada") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Praznik rada", hols)
		}
	}
}

func TestRS_LA_005_DanPobede(t *testing.T) {
	dates := []string{"2017-5-9"}
	opts := holidays.Options{Regions: []string{"rs_la"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Dan pobede") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Dan pobede", hols)
		}
	}
}

func TestRS_LA_006_Vidovdan(t *testing.T) {
	dates := []string{"2017-6-28"}
	opts := holidays.Options{Regions: []string{"rs_la"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Vidovdan") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Vidovdan", hols)
		}
	}
}

func TestRS_LA_007_DanPrimirja(t *testing.T) {
	dates := []string{"2017-11-11"}
	opts := holidays.Options{Regions: []string{"rs_la"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Dan primirja") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Dan primirja", hols)
		}
	}
}

func TestRS_LA_008_VelikiPetak(t *testing.T) {
	dates := []string{"2017-4-14", "2018-4-6", "2019-4-26"}
	opts := holidays.Options{Regions: []string{"rs_la"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Veliki Petak") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Veliki Petak", hols)
		}
	}
}

func TestRS_LA_009_VelikaSubota(t *testing.T) {
	dates := []string{"2017-4-15", "2018-4-7", "2019-4-27"}
	opts := holidays.Options{Regions: []string{"rs_la"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Velika Subota") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Velika Subota", hols)
		}
	}
}

func TestRS_LA_010_Uskrs(t *testing.T) {
	dates := []string{"2017-4-16", "2018-4-8", "2019-4-28"}
	opts := holidays.Options{Regions: []string{"rs_la"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Uskrs") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Uskrs", hols)
		}
	}
}

func TestRS_LA_011_VaskrsniPonedeljak(t *testing.T) {
	dates := []string{"2017-4-17", "2018-4-9", "2019-4-29"}
	opts := holidays.Options{Regions: []string{"rs_la"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Vaskrsni ponedeljak") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Vaskrsni ponedeljak", hols)
		}
	}
}
