// Code generated by gen-holidays from definitions/se.yaml@v7.0.0. DO NOT EDIT.

package definitions_test

import (
	"testing"

	holidays "github.com/ppeble/go-holidays/pkg"
)

func TestSE_000_Nyårsdagen(t *testing.T) {
	dates := []string{"2008-01-01"}
	opts := holidays.Options{Regions: []string{"se"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Nyårsdagen") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Nyårsdagen", hols)
		}
	}
}

func TestSE_001_TrettondedagJul(t *testing.T) {
	dates := []string{"2008-01-06"}
	opts := holidays.Options{Regions: []string{"se"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Trettondedag jul") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Trettondedag jul", hols)
		}
	}
}

func TestSE_002_Långfredagen(t *testing.T) {
	dates := []string{"2008-03-21"}
	opts := holidays.Options{Regions: []string{"se"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Långfredagen") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Långfredagen", hols)
		}
	}
}

func TestSE_003_Påskafton(t *testing.T) {
	dates := []string{"2008-03-22"}
	opts := holidays.Options{Regions: []string{"se"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Påskafton") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Påskafton", hols)
		}
	}
}

func TestSE_004_Påskdagen(t *testing.T) {
	dates := []string{"2008-03-23"}
	opts := holidays.Options{Regions: []string{"se"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Påskdagen") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Påskdagen", hols)
		}
	}
}

func TestSE_005_AnnandagPåsk(t *testing.T) {
	dates := []string{"2008-03-24"}
	opts := holidays.Options{Regions: []string{"se"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Annandag påsk") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Annandag påsk", hols)
		}
	}
}

func TestSE_006_KristiHimmelsfärdsdag(t *testing.T) {
	dates := []string{"2008-05-01"}
	opts := holidays.Options{Regions: []string{"se"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Kristi himmelsfärdsdag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Kristi himmelsfärdsdag", hols)
		}
	}
}

func TestSE_007_Pingstdagen(t *testing.T) {
	dates := []string{"2008-05-11"}
	opts := holidays.Options{Regions: []string{"se"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Pingstdagen") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Pingstdagen", hols)
		}
	}
}

func TestSE_008_Nationaldagen(t *testing.T) {
	dates := []string{"2008-06-06"}
	opts := holidays.Options{Regions: []string{"se"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Nationaldagen") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Nationaldagen", hols)
		}
	}
}

func TestSE_009_Midsommardagen(t *testing.T) {
	dates := []string{"2005-06-25"}
	opts := holidays.Options{Regions: []string{"se"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Midsommardagen") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Midsommardagen", hols)
		}
	}
}

func TestSE_010_Midsommardagen(t *testing.T) {
	dates := []string{"2006-06-24"}
	opts := holidays.Options{Regions: []string{"se"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Midsommardagen") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Midsommardagen", hols)
		}
	}
}

func TestSE_011_Midsommarafton(t *testing.T) {
	dates := []string{"2006-06-23"}
	opts := holidays.Options{Regions: []string{"se"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Midsommarafton") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Midsommarafton", hols)
		}
	}
}

func TestSE_012_Midsommardagen(t *testing.T) {
	dates := []string{"2007-06-23"}
	opts := holidays.Options{Regions: []string{"se"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Midsommardagen") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Midsommardagen", hols)
		}
	}
}

func TestSE_013_Midsommarafton(t *testing.T) {
	dates := []string{"2007-06-22"}
	opts := holidays.Options{Regions: []string{"se"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Midsommarafton") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Midsommarafton", hols)
		}
	}
}

func TestSE_014_Midsommardagen(t *testing.T) {
	dates := []string{"2008-06-21"}
	opts := holidays.Options{Regions: []string{"se"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Midsommardagen") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Midsommardagen", hols)
		}
	}
}

func TestSE_015_Midsommarafton(t *testing.T) {
	dates := []string{"2008-06-20"}
	opts := holidays.Options{Regions: []string{"se"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Midsommarafton") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Midsommarafton", hols)
		}
	}
}

func TestSE_016_AllaHelgonsDag(t *testing.T) {
	dates := []string{"2005-11-05"}
	opts := holidays.Options{Regions: []string{"se"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Alla helgons dag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Alla helgons dag", hols)
		}
	}
}

func TestSE_017_AllaHelgonsDag(t *testing.T) {
	dates := []string{"2006-11-04"}
	opts := holidays.Options{Regions: []string{"se"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Alla helgons dag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Alla helgons dag", hols)
		}
	}
}

func TestSE_018_AllaHelgonsDag(t *testing.T) {
	dates := []string{"2007-11-03"}
	opts := holidays.Options{Regions: []string{"se"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Alla helgons dag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Alla helgons dag", hols)
		}
	}
}

func TestSE_019_AllaHelgonsDag(t *testing.T) {
	dates := []string{"2008-11-01"}
	opts := holidays.Options{Regions: []string{"se"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Alla helgons dag") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Alla helgons dag", hols)
		}
	}
}

func TestSE_020_Julafton(t *testing.T) {
	dates := []string{"2008-12-24"}
	opts := holidays.Options{Regions: []string{"se"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Julafton") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Julafton", hols)
		}
	}
}

func TestSE_021_Juldagen(t *testing.T) {
	dates := []string{"2008-12-25"}
	opts := holidays.Options{Regions: []string{"se"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Juldagen") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Juldagen", hols)
		}
	}
}

func TestSE_022_AnnandagJul(t *testing.T) {
	dates := []string{"2008-12-26"}
	opts := holidays.Options{Regions: []string{"se"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Annandag jul") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Annandag jul", hols)
		}
	}
}

func TestSE_023_Nyårsafton(t *testing.T) {
	dates := []string{"2008-12-31"}
	opts := holidays.Options{Regions: []string{"se"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Nyårsafton") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Nyårsafton", hols)
		}
	}
}
