// Code generated by gen-holidays from definitions/sg.yaml@v8.0.1. DO NOT EDIT.

package definitions

import (
	"github.com/ppeble/go-holidays/pkg/definition"
	"github.com/ppeble/go-holidays/pkg/engine"
)

var sgRules = []definition.HolidayRule{
	{
		Name:             "Good Friday",
		Regions:          []string{"sg"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -2,
	},
	{
		Name:     "New Year's Day",
		Regions:  []string{"sg"},
		Month:    1,
		Mday:     1,
		Wday:     -1,
		Observed: "to_weekday_if_weekend",
	},
	{
		Name:    "Valentine's Day",
		Regions: []string{"sg"},
		Month:   2,
		Mday:    14,
		Wday:    -1,
		Type:    definition.Informal,
	},
	{
		Name:    "Total Defence Day",
		Regions: []string{"sg"},
		Month:   2,
		Mday:    15,
		Wday:    -1,
		Type:    definition.Informal,
	},
	{
		Name:    "Labour Day",
		Regions: []string{"sg"},
		Month:   5,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:     "National Day",
		Regions:  []string{"sg"},
		Month:    8,
		Mday:     9,
		Wday:     -1,
		Observed: "to_weekday_if_weekend",
	},
	{
		Name:     "Christmas Day",
		Regions:  []string{"sg"},
		Month:    12,
		Mday:     25,
		Wday:     -1,
		Observed: "to_weekday_if_weekend",
	},
}

func init() {
	engine.RegisterCountry("sg", sgRules)
}
