// Code generated by gen-holidays from definitions/sk.yaml@v8.0.0. DO NOT EDIT.

package definitions_test

import (
	"testing"

	holidays "github.com/ppeble/go-holidays/pkg"
)

func TestSK_000_NovýRok(t *testing.T) {
	dates := []string{"2025-01-01"}
	opts := holidays.Options{Regions: []string{"sk"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Nový rok") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Nový rok", hols)
		}
	}
}

func TestSK_001_ZjaveniePánaTrajaKráli(t *testing.T) {
	dates := []string{"2025-01-06"}
	opts := holidays.Options{Regions: []string{"sk"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Zjavenie Pána (Traja králi)") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Zjavenie Pána (Traja králi)", hols)
		}
	}
}

func TestSK_002_VeľkýPiatok(t *testing.T) {
	dates := []string{"2013-03-29"}
	opts := holidays.Options{Regions: []string{"sk"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Veľký piatok") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Veľký piatok", hols)
		}
	}
}

func TestSK_003_VeľkonočnýPondelok(t *testing.T) {
	dates := []string{"2013-04-01"}
	opts := holidays.Options{Regions: []string{"sk"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Veľkonočný pondelok") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Veľkonočný pondelok", hols)
		}
	}
}

func TestSK_004_SviatokPráce(t *testing.T) {
	dates := []string{"2025-05-01"}
	opts := holidays.Options{Regions: []string{"sk"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Sviatok práce") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Sviatok práce", hols)
		}
	}
}

func TestSK_005_DeňVíťazstvaNadFašizmom(t *testing.T) {
	dates := []string{"2025-05-08"}
	opts := holidays.Options{Regions: []string{"sk"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Deň víťazstva nad fašizmom") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Deň víťazstva nad fašizmom", hols)
		}
	}
}

func TestSK_006_SviatokSvätéhoCyrilaASvätéhoMetoda(t *testing.T) {
	dates := []string{"2025-07-05"}
	opts := holidays.Options{Regions: []string{"sk"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Sviatok svätého Cyrila a svätého Metoda") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Sviatok svätého Cyrila a svätého Metoda", hols)
		}
	}
}

func TestSK_007_VýročieSlovenskéhoNárodnéhoPovstania(t *testing.T) {
	dates := []string{"2025-08-29"}
	opts := holidays.Options{Regions: []string{"sk"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Výročie Slovenského národného povstania") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Výročie Slovenského národného povstania", hols)
		}
	}
}

func TestSK_008_SedembolestnáPannaMária(t *testing.T) {
	dates := []string{"2025-09-15"}
	opts := holidays.Options{Regions: []string{"sk"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Sedembolestná Panna Mária") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Sedembolestná Panna Mária", hols)
		}
	}
}

func TestSK_009_SviatokVšetkýchSvätých(t *testing.T) {
	dates := []string{"2025-11-01"}
	opts := holidays.Options{Regions: []string{"sk"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Sviatok všetkých svätých") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Sviatok všetkých svätých", hols)
		}
	}
}

func TestSK_010_ŠtedrýDeň(t *testing.T) {
	dates := []string{"2025-12-24"}
	opts := holidays.Options{Regions: []string{"sk"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Štedrý deň") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Štedrý deň", hols)
		}
	}
}

func TestSK_011_1SviatokVianočný(t *testing.T) {
	dates := []string{"2025-12-25"}
	opts := holidays.Options{Regions: []string{"sk"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "1. sviatok vianočný") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "1. sviatok vianočný", hols)
		}
	}
}

func TestSK_012_2SviatokVianočný(t *testing.T) {
	dates := []string{"2025-12-26"}
	opts := holidays.Options{Regions: []string{"sk"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "2. sviatok vianočný") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "2. sviatok vianočný", hols)
		}
	}
}
