// Code generated by gen-holidays from definitions/th.yaml@v7.0.0. DO NOT EDIT.

package definitions_test

import (
	"testing"

	holidays "github.com/ppeble/go-holidays/pkg"
)

func TestTH_000_วนจกร(t *testing.T) {
	dates := []string{"2019-04-06"}
	opts := holidays.Options{Regions: []string{"th"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "วันจักรี") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "วันจักรี", hols)
		}
	}
}

func TestTH_001_วนสงกรานต(t *testing.T) {
	dates := []string{"2019-04-13", "2019-04-14", "2019-04-15"}
	opts := holidays.Options{Regions: []string{"th"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "วันสงกรานต์") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "วันสงกรานต์", hols)
		}
	}
}

func TestTH_002_วนเฉลมพระชนมพรรษาสมเดจพระเจาอยหวมหาวชราลงกรณบดนทรเทพยวรางกร(t *testing.T) {
	dates := []string{"2019-07-28"}
	opts := holidays.Options{Regions: []string{"th"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "วันเฉลิมพระชนมพรรษาสมเด็จพระเจ้าอยู่หัวมหาวชิราลงกรณ บดินทรเทพยวรางกูร") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "วันเฉลิมพระชนมพรรษาสมเด็จพระเจ้าอยู่หัวมหาวชิราลงกรณ บดินทรเทพยวรางกูร", hols)
		}
	}
}

func TestTH_003_วนเฉลมพระชนมพรรษาสมเดจพระนางเจาสรกตพระบรมราชนนาถในรชกาลท๙(t *testing.T) {
	dates := []string{"2007-08-12"}
	opts := holidays.Options{Regions: []string{"th"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "วันเฉลิมพระชนมพรรษาสมเด็จพระนางเจ้าสิริกิติ์ พระบรมราชินีนาถในรัชกาลที่ ๙") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "วันเฉลิมพระชนมพรรษาสมเด็จพระนางเจ้าสิริกิติ์ พระบรมราชินีนาถในรัชกาลที่ ๙", hols)
		}
	}
}

func TestTH_004_วนคลายวนสวรรคตพระบาทสมเดจพระปรมนทรมหาภมพลอดลยเดชบรมนาถบพตร(t *testing.T) {
	dates := []string{"2019-10-13"}
	opts := holidays.Options{Regions: []string{"th"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "วันคล้ายวันสวรรคตพระบาทสมเด็จพระปรมินทรมหาภูมิพลอดุลยเดช บรมนาถบพิตร") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "วันคล้ายวันสวรรคตพระบาทสมเด็จพระปรมินทรมหาภูมิพลอดุลยเดช บรมนาถบพิตร", hols)
		}
	}
}

func TestTH_005_วนปยมหาราช(t *testing.T) {
	dates := []string{"2019-10-23"}
	opts := holidays.Options{Regions: []string{"th"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "วันปิยมหาราช") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "วันปิยมหาราช", hols)
		}
	}
}

func TestTH_006_วนคลายวนเฉลมพระชนมพรรษาพระบาทสมเดจพระปรมนทรมหาภมพลอดลยเดชบรมนาถบพตร(t *testing.T) {
	dates := []string{"2019-12-05"}
	opts := holidays.Options{Regions: []string{"th"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "วันคล้ายวันเฉลิมพระชนมพรรษาพระบาทสมเด็จพระปรมินทรมหาภูมิพลอดุลยเดช บรมนาถบพิตร") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "วันคล้ายวันเฉลิมพระชนมพรรษาพระบาทสมเด็จพระปรมินทรมหาภูมิพลอดุลยเดช บรมนาถบพิตร", hols)
		}
	}
}

func TestTH_007_วนรฐธรรมนญ(t *testing.T) {
	dates := []string{"2019-12-10"}
	opts := holidays.Options{Regions: []string{"th"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "วันรัฐธรรมนูญ") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "วันรัฐธรรมนูญ", hols)
		}
	}
}

func TestTH_008_วนสนป(t *testing.T) {
	dates := []string{"2019-12-31"}
	opts := holidays.Options{Regions: []string{"th"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "วันสิ้นปี") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "วันสิ้นปี", hols)
		}
	}
}
