// Code generated by gen-holidays from definitions/tn.yaml@v6.1.1. DO NOT EDIT.

package definitions_test

import (
	"testing"

	holidays "github.com/ppeble/go-holidays/pkg"
)

func TestTN_000_JourDeLAn(t *testing.T) {
	dates := []string{"2016-01-01"}
	opts := holidays.Options{Regions: []string{"tn"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Jour de l'an") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Jour de l'an", hols)
		}
	}
}

func TestTN_001_FêteDeLaRévolutionEtDeLaJeunesse(t *testing.T) {
	dates := []string{"2016-01-14"}
	opts := holidays.Options{Regions: []string{"tn"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Fête de la Révolution et de la Jeunesse") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Fête de la Révolution et de la Jeunesse", hols)
		}
	}
}

func TestTN_002_FêteDeLIndépendance(t *testing.T) {
	dates := []string{"2016-03-20"}
	opts := holidays.Options{Regions: []string{"tn"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Fête de l'Indépendance") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Fête de l'Indépendance", hols)
		}
	}
}

func TestTN_003_JournéeDesMartyrs(t *testing.T) {
	dates := []string{"2016-04-09"}
	opts := holidays.Options{Regions: []string{"tn"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Journée des Martyrs") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Journée des Martyrs", hols)
		}
	}
}

func TestTN_004_FêteDuTravail(t *testing.T) {
	dates := []string{"2016-05-01"}
	opts := holidays.Options{Regions: []string{"tn"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Fête du travail") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Fête du travail", hols)
		}
	}
}

func TestTN_005_FêteDeLaRépublique(t *testing.T) {
	dates := []string{"2016-07-25"}
	opts := holidays.Options{Regions: []string{"tn"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Fête de la République") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Fête de la République", hols)
		}
	}
}

func TestTN_006_FêteDeLaFemmeEtDeLaFamille(t *testing.T) {
	dates := []string{"2016-08-13"}
	opts := holidays.Options{Regions: []string{"tn"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Fête de la Femme et de la Famille") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Fête de la Femme et de la Famille", hols)
		}
	}
}

func TestTN_007_FêteDeLÉvacuation(t *testing.T) {
	dates := []string{"2016-10-15"}
	opts := holidays.Options{Regions: []string{"tn"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Fête de l'Évacuation") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Fête de l'Évacuation", hols)
		}
	}
}
