// Code generated by gen-holidays from definitions/tsx.yaml@v8.0.0. DO NOT EDIT.

package definitions_test

import (
	"testing"

	holidays "github.com/ppeble/go-holidays/pkg"
)

func TestTSX_000_NewYearSDay(t *testing.T) {
	dates := []string{"2008-01-01"}
	opts := holidays.Options{Regions: []string{"tsx"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "New Year's Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols)
		}
	}
}

func TestTSX_001_GoodFriday(t *testing.T) {
	dates := []string{"2008-03-21"}
	opts := holidays.Options{Regions: []string{"tsx"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Good Friday") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Good Friday", hols)
		}
	}
}

func TestTSX_002_CanadaDay(t *testing.T) {
	dates := []string{"2008-07-01"}
	opts := holidays.Options{Regions: []string{"tsx"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Canada Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Canada Day", hols)
		}
	}
}

func TestTSX_003_LabourDay(t *testing.T) {
	dates := []string{"2008-09-01"}
	opts := holidays.Options{Regions: []string{"tsx"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Labour Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Labour Day", hols)
		}
	}
}

func TestTSX_004_ChristmasDay(t *testing.T) {
	dates := []string{"2008-12-25"}
	opts := holidays.Options{Regions: []string{"tsx"}, Informal: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Christmas Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols)
		}
	}
}

func TestTSX_005_Negative(t *testing.T) {
	dates := []string{"1970-02-16"}
	opts := holidays.Options{Regions: []string{"tsx"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if len(hols) > 0 {
			t.Errorf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols)
		}
	}
}

func TestTSX_006_Negative(t *testing.T) {
	dates := []string{"1988-02-15"}
	opts := holidays.Options{Regions: []string{"tsx"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if len(hols) > 0 {
			t.Errorf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols)
		}
	}
}

func TestTSX_007_Negative(t *testing.T) {
	dates := []string{"1989-02-20"}
	opts := holidays.Options{Regions: []string{"tsx"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if len(hols) > 0 {
			t.Errorf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols)
		}
	}
}

func TestTSX_008_Negative(t *testing.T) {
	dates := []string{"2006-02-20"}
	opts := holidays.Options{Regions: []string{"tsx"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if len(hols) > 0 {
			t.Errorf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols)
		}
	}
}

func TestTSX_009_Negative(t *testing.T) {
	dates := []string{"2007-02-19"}
	opts := holidays.Options{Regions: []string{"tsx"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if len(hols) > 0 {
			t.Errorf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols)
		}
	}
}

func TestTSX_010_NewYearSDay(t *testing.T) {
	dates := []string{"2011-01-03"}
	opts := holidays.Options{Regions: []string{"tsx"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "New Year's Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols)
		}
	}
}

func TestTSX_011_NewYearSDay(t *testing.T) {
	dates := []string{"2012-01-02"}
	opts := holidays.Options{Regions: []string{"tsx"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "New Year's Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols)
		}
	}
}

func TestTSX_012_NewYearSDay(t *testing.T) {
	dates := []string{"2016-01-01"}
	opts := holidays.Options{Regions: []string{"tsx"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "New Year's Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols)
		}
	}
}

func TestTSX_013_CanadaDay(t *testing.T) {
	dates := []string{"2011-07-01"}
	opts := holidays.Options{Regions: []string{"tsx"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Canada Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Canada Day", hols)
		}
	}
}

func TestTSX_014_CanadaDay(t *testing.T) {
	dates := []string{"2012-07-02"}
	opts := holidays.Options{Regions: []string{"tsx"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Canada Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Canada Day", hols)
		}
	}
}

func TestTSX_015_CanadaDay(t *testing.T) {
	dates := []string{"2017-07-03"}
	opts := holidays.Options{Regions: []string{"tsx"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Canada Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Canada Day", hols)
		}
	}
}

func TestTSX_016_ChristmasDay(t *testing.T) {
	dates := []string{"2010-12-25"}
	opts := holidays.Options{Regions: []string{"tsx"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Christmas Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols)
		}
	}
}

func TestTSX_017_ChristmasDay(t *testing.T) {
	dates := []string{"2018-12-25"}
	opts := holidays.Options{Regions: []string{"tsx"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Christmas Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols)
		}
	}
}

func TestTSX_018_ChristmasDay(t *testing.T) {
	dates := []string{"2022-12-25"}
	opts := holidays.Options{Regions: []string{"tsx"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Christmas Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols)
		}
	}
}

func TestTSX_019_Negative(t *testing.T) {
	dates := []string{"2022-12-25"}
	opts := holidays.Options{Regions: []string{"tsx"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if len(hols) > 0 {
			t.Errorf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols)
		}
	}
}

func TestTSX_020_ChristmasDay(t *testing.T) {
	dates := []string{"2010-12-24"}
	opts := holidays.Options{Regions: []string{"tsx"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Christmas Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols)
		}
	}
}

func TestTSX_021_ChristmasDay(t *testing.T) {
	dates := []string{"2012-12-25"}
	opts := holidays.Options{Regions: []string{"tsx"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Christmas Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols)
		}
	}
}

func TestTSX_022_ChristmasDay(t *testing.T) {
	dates := []string{"2016-12-26"}
	opts := holidays.Options{Regions: []string{"tsx"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Christmas Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols)
		}
	}
}

func TestTSX_023_ChristmasDay(t *testing.T) {
	dates := []string{"2021-12-27"}
	opts := holidays.Options{Regions: []string{"tsx"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Christmas Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols)
		}
	}
}

func TestTSX_024_ChristmasDay(t *testing.T) {
	dates := []string{"2022-12-26"}
	opts := holidays.Options{Regions: []string{"tsx"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Christmas Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols)
		}
	}
}

func TestTSX_025_BoxingDay(t *testing.T) {
	dates := []string{"2010-12-27", "2012-12-26", "2015-12-28"}
	opts := holidays.Options{Regions: []string{"tsx"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Boxing Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Boxing Day", hols)
		}
	}
}

func TestTSX_026_VictoriaDay(t *testing.T) {
	dates := []string{"2022-05-23", "2021-05-24"}
	opts := holidays.Options{Regions: []string{"tsx"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Victoria Day") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Victoria Day", hols)
		}
	}
}

func TestTSX_027_Negative(t *testing.T) {
	dates := []string{"2015-05-24"}
	opts := holidays.Options{Regions: []string{"tsx"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if len(hols) > 0 {
			t.Errorf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols)
		}
	}
}
