// Code generated by gen-holidays from definitions/ua.yaml@v7.0.0. DO NOT EDIT.

package definitions_test

import (
	"testing"

	holidays "github.com/ppeble/go-holidays/pkg"
)

func TestUA_000_НовийРік(t *testing.T) {
	dates := []string{"2018-01-01"}
	opts := holidays.Options{Regions: []string{"ua"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Новий Рік") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Новий Рік", hols)
		}
	}
}

func TestUA_001_РіздвоХристове(t *testing.T) {
	dates := []string{"2018-01-07"}
	opts := holidays.Options{Regions: []string{"ua"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Різдво Христове") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Різдво Христове", hols)
		}
	}
}

func TestUA_002_РіздвоХристове(t *testing.T) {
	dates := []string{"2018-01-08"}
	opts := holidays.Options{Regions: []string{"ua"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Різдво Христове") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Різдво Христове", hols)
		}
	}
}

func TestUA_003_МіжнароднийЖіночийДень(t *testing.T) {
	dates := []string{"2018-03-08"}
	opts := holidays.Options{Regions: []string{"ua"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Міжнародний жіночий день") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Міжнародний жіночий день", hols)
		}
	}
}

func TestUA_004_Великдень(t *testing.T) {
	dates := []string{"2018-04-08"}
	opts := holidays.Options{Regions: []string{"ua"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Великдень") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Великдень", hols)
		}
	}
}

func TestUA_005_Великдень(t *testing.T) {
	dates := []string{"2018-04-09"}
	opts := holidays.Options{Regions: []string{"ua"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Великдень") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Великдень", hols)
		}
	}
}

func TestUA_006_ДеньПраці(t *testing.T) {
	dates := []string{"2018-05-01"}
	opts := holidays.Options{Regions: []string{"ua"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "День праці") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "День праці", hols)
		}
	}
}

func TestUA_007_ДеньПеремогиНадНацизмомУДругійСвітовійВійні(t *testing.T) {
	dates := []string{"2018-05-09"}
	opts := holidays.Options{Regions: []string{"ua"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "День перемоги над нацизмом у Другій світовій війні") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "День перемоги над нацизмом у Другій світовій війні", hols)
		}
	}
}

func TestUA_008_Трійця(t *testing.T) {
	dates := []string{"2018-05-27"}
	opts := holidays.Options{Regions: []string{"ua"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Трійця") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Трійця", hols)
		}
	}
}

func TestUA_009_Трійця(t *testing.T) {
	dates := []string{"2018-05-28"}
	opts := holidays.Options{Regions: []string{"ua"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Трійця") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Трійця", hols)
		}
	}
}

func TestUA_010_ДеньКонституції(t *testing.T) {
	dates := []string{"2018-06-28"}
	opts := holidays.Options{Regions: []string{"ua"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "День Конституції") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "День Конституції", hols)
		}
	}
}

func TestUA_011_ДеньНезалежності(t *testing.T) {
	dates := []string{"2018-08-24"}
	opts := holidays.Options{Regions: []string{"ua"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "День Незалежності") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "День Незалежності", hols)
		}
	}
}

func TestUA_012_ДеньЗахисникаУкраїни(t *testing.T) {
	dates := []string{"2018-10-14"}
	opts := holidays.Options{Regions: []string{"ua"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "День захисника України") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "День захисника України", hols)
		}
	}
}

func TestUA_013_ДеньЗахисникаУкраїни(t *testing.T) {
	dates := []string{"2018-10-15"}
	opts := holidays.Options{Regions: []string{"ua"}, Observed: true}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "День захисника України") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "День захисника України", hols)
		}
	}
}

func TestUA_014_РіздвоХристове(t *testing.T) {
	dates := []string{"2018-12-25"}
	opts := holidays.Options{Regions: []string{"ua"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Різдво Христове") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Різдво Христове", hols)
		}
	}
}
