// Code generated by gen-holidays from definitions/ve.yaml@v7.0.0. DO NOT EDIT.

package definitions_test

import (
	"testing"

	holidays "github.com/ppeble/go-holidays/pkg"
)

func TestVE_000_AñoNuevo(t *testing.T) {
	dates := []string{"2013-01-01"}
	opts := holidays.Options{Regions: []string{"ve"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Año Nuevo") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Año Nuevo", hols)
		}
	}
}

func TestVE_001_LunesCarnaval(t *testing.T) {
	dates := []string{"2013-02-11"}
	opts := holidays.Options{Regions: []string{"ve"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Lunes Carnaval") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Lunes Carnaval", hols)
		}
	}
}

func TestVE_002_MartesCarnaval(t *testing.T) {
	dates := []string{"2013-02-12"}
	opts := holidays.Options{Regions: []string{"ve"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Martes Carnaval") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Martes Carnaval", hols)
		}
	}
}

func TestVE_003_JuevesSanto(t *testing.T) {
	dates := []string{"2013-03-28"}
	opts := holidays.Options{Regions: []string{"ve"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Jueves Santo") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Jueves Santo", hols)
		}
	}
}

func TestVE_004_ViernesSanto(t *testing.T) {
	dates := []string{"2013-03-29"}
	opts := holidays.Options{Regions: []string{"ve"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Viernes Santo") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Viernes Santo", hols)
		}
	}
}

func TestVE_005_DeclaraciónIndependencia(t *testing.T) {
	dates := []string{"2013-04-19"}
	opts := holidays.Options{Regions: []string{"ve"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Declaración Independencia") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Declaración Independencia", hols)
		}
	}
}

func TestVE_006_DíaDelTrabajador(t *testing.T) {
	dates := []string{"2013-05-01"}
	opts := holidays.Options{Regions: []string{"ve"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Día del Trabajador") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día del Trabajador", hols)
		}
	}
}

func TestVE_007_AniversarioBatallaDeCarabobo(t *testing.T) {
	dates := []string{"2013-06-24"}
	opts := holidays.Options{Regions: []string{"ve"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Aniversario Batalla de Carabobo") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Aniversario Batalla de Carabobo", hols)
		}
	}
}

func TestVE_008_DíaDeLaIndependencia(t *testing.T) {
	dates := []string{"2013-07-05"}
	opts := holidays.Options{Regions: []string{"ve"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Día de la Independencia") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de la Independencia", hols)
		}
	}
}

func TestVE_009_NatalicioDeSimónBolívar(t *testing.T) {
	dates := []string{"2013-07-24"}
	opts := holidays.Options{Regions: []string{"ve"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Natalicio de Simón Bolívar") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Natalicio de Simón Bolívar", hols)
		}
	}
}

func TestVE_010_DíaDeLaResistenciaIndígena(t *testing.T) {
	dates := []string{"2013-10-12"}
	opts := holidays.Options{Regions: []string{"ve"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Día de la Resistencia Indígena") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de la Resistencia Indígena", hols)
		}
	}
}

func TestVE_011_DíaDeNavidad(t *testing.T) {
	dates := []string{"2013-12-25"}
	opts := holidays.Options{Regions: []string{"ve"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Día de Navidad") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de Navidad", hols)
		}
	}
}
