// Code generated by gen-holidays from definitions/vi.yaml@v6.1.1. DO NOT EDIT.

package definitions

import (
	"github.com/ppeble/go-holidays/pkg/definition"
	"github.com/ppeble/go-holidays/pkg/engine"
)

var viRules = []definition.HolidayRule{
	{
		Name:    "Tết dương lịch",
		Regions: []string{"vi"},
		Month:   1,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:         "Giỗ tổ Hùng Vương",
		Regions:      []string{"vi"},
		Month:        3,
		Mday:         10,
		Wday:         -1,
		Function:     "lunar_to_solar",
		FunctionArgs: []string{"year", "month", "day", "region"},
	},
	{
		Name:    "Ngày Giải phóng miền Nam, thống nhất đất nước",
		Regions: []string{"vi"},
		Month:   4,
		Mday:    30,
		Wday:    -1,
	},
	{
		Name:    "Ngày Quốc tế Lao động",
		Regions: []string{"vi"},
		Month:   5,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:    "Quốc khánh",
		Regions: []string{"vi"},
		Month:   9,
		Mday:    2,
		Wday:    -1,
	},
}

func init() {
	engine.RegisterCountry("vi", viRules)
}
