// Code generated by gen-holidays from definitions/vi.yaml@v7.0.0. DO NOT EDIT.

package definitions_test

import (
	"testing"

	holidays "github.com/ppeble/go-holidays/pkg"
)

func TestVI_000_TếtDươngLịch(t *testing.T) {
	dates := []string{"2014-01-01"}
	opts := holidays.Options{Regions: []string{"vi"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Tết dương lịch") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Tết dương lịch", hols)
		}
	}
}

func TestVI_001_NgàyGiảiPhóngMiềnNamThốngNhấtĐấtNước(t *testing.T) {
	dates := []string{"2014-04-30"}
	opts := holidays.Options{Regions: []string{"vi"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Ngày Giải phóng miền Nam, thống nhất đất nước") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Ngày Giải phóng miền Nam, thống nhất đất nước", hols)
		}
	}
}

func TestVI_002_NgàyQuốcTếLaoĐộng(t *testing.T) {
	dates := []string{"2014-05-01"}
	opts := holidays.Options{Regions: []string{"vi"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Ngày Quốc tế Lao động") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Ngày Quốc tế Lao động", hols)
		}
	}
}

func TestVI_003_QuốcKhánh(t *testing.T) {
	dates := []string{"2014-09-02"}
	opts := holidays.Options{Regions: []string{"vi"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Quốc khánh") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Quốc khánh", hols)
		}
	}
}

func TestVI_004_GiỗTổHùngVương(t *testing.T) {
	dates := []string{"2017-04-06", "2018-03-27"}
	opts := holidays.Options{Regions: []string{"vi"}}
	for _, s := range dates {
		d, err := parseFlex(s)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		hols, err := holidays.On(d, opts)
		if err != nil {
			t.Fatalf("On(%s): %v", s, err)
		}
		if !hasNamed(hols, "Giỗ tổ Hùng Vương") {
			t.Errorf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Giỗ tổ Hùng Vương", hols)
		}
	}
}
