package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"strconv"
	"strings"
	"unicode"
)

// EmitTests returns the Go source for pkg/definitions/<country>_test.go.
func EmitTests(rf *RegionFile) ([]byte, error) {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by gen-holidays from definitions/%s.yaml@%s. DO NOT EDIT.\n\n", rf.Country, SourceTag)
	fmt.Fprintln(&buf, "package definitions_test")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "import (")
	fmt.Fprintln(&buf, "\t\"testing\"")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "\tholidays \"github.com/ppeble/go-holidays/pkg\"")
	fmt.Fprintln(&buf, ")")
	fmt.Fprintln(&buf)

	for i, ts := range rf.Tests {
		writeTestFunc(&buf, rf.Country, i, ts)
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.Bytes(), fmt.Errorf("gofmt %s_test: %w (raw output kept for debugging)", rf.Country, err)
	}
	return src, nil
}

// EmitTestHelpers returns the Go source for pkg/definitions/helpers_test.go.
// This file is regenerated on every run and is the single source of shared
// helpers + the blank import that triggers all region init() functions.
func EmitTestHelpers() []byte {
	return []byte(`// Code generated by gen-holidays. DO NOT EDIT.

package definitions_test

import (
	"time"

	holidays "github.com/ppeble/go-holidays/pkg"
	_ "github.com/ppeble/go-holidays/pkg/definitions"
)

func parseFlex(s string) (time.Time, error) {
	return time.Parse("2006-1-2", s)
}

func hasNamed(hs []holidays.Holiday, name string) bool {
	for _, h := range hs {
		if h.Name == name {
			return true
		}
	}
	return false
}
`)
}

func writeTestFunc(buf *bytes.Buffer, country string, idx int, ts TestSpec) {
	hint := testHint(ts)
	name := fmt.Sprintf("Test%s_%03d_%s", strings.ToUpper(country), idx, hint)
	fmt.Fprintf(buf, "func %s(t *testing.T) {\n", name)
	fmt.Fprintf(buf, "\tdates := %s\n", stringSliceLit(ts.Dates))
	fmt.Fprintf(buf, "\topts := holidays.Options{Regions: %s", stringSliceLit(ts.Regions))
	for _, o := range ts.Options {
		switch o {
		case "informal":
			fmt.Fprint(buf, ", Informal: true")
		case "observed":
			fmt.Fprint(buf, ", Observed: true")
		}
	}
	fmt.Fprintln(buf, "}")
	buf.WriteString("\tfor _, s := range dates {\n")
	buf.WriteString("\t\td, err := parseFlex(s)\n")
	buf.WriteString("\t\tif err != nil { t.Fatalf(\"parse %q: %v\", s, err) }\n")
	buf.WriteString("\t\thols, err := holidays.On(d, opts)\n")
	buf.WriteString("\t\tif err != nil { t.Fatalf(\"On(%s): %v\", s, err) }\n")

	switch {
	case ts.Expected.Name != "":
		fmt.Fprintf(buf, "\t\tif !hasNamed(hols, %s) {\n", strconv.Quote(ts.Expected.Name))
		fmt.Fprintf(buf, "\t\t\tt.Errorf(\"On(%%s, %%v): want holiday %%q, got %%v\", s, opts.Regions, %s, hols)\n", strconv.Quote(ts.Expected.Name))
		buf.WriteString("\t\t}\n")
	case ts.Expected.Holiday != nil && !*ts.Expected.Holiday:
		buf.WriteString("\t\tif len(hols) > 0 {\n")
		buf.WriteString("\t\t\tt.Errorf(\"On(%s, %v): expected no holiday, got %v\", s, opts.Regions, hols)\n")
		buf.WriteString("\t\t}\n")
	case ts.Expected.Holiday != nil && *ts.Expected.Holiday:
		buf.WriteString("\t\tif len(hols) == 0 {\n")
		buf.WriteString("\t\t\tt.Errorf(\"On(%s, %v): expected a holiday, got none\", s, opts.Regions)\n")
		buf.WriteString("\t\t}\n")
	}
	buf.WriteString("\t}\n")
	buf.WriteString("}\n\n")
}

func testHint(ts TestSpec) string {
	if ts.Expected.Name != "" {
		return sanitizeIdent(ts.Expected.Name)
	}
	if ts.Expected.Holiday != nil && !*ts.Expected.Holiday {
		return "Negative"
	}
	return "Positive"
}

// sanitizeIdent makes a Go-safe identifier fragment from arbitrary text.
func sanitizeIdent(s string) string {
	var b strings.Builder
	upper := true
	for _, r := range s {
		switch {
		case unicode.IsLetter(r) || unicode.IsDigit(r):
			if upper {
				b.WriteRune(unicode.ToUpper(r))
				upper = false
			} else {
				b.WriteRune(r)
			}
		default:
			upper = true
		}
	}
	if b.Len() == 0 {
		return "Unnamed"
	}
	return b.String()
}
